export const messageKinds = ["plain", "interpolation", "plural", "contextual/select", "rich"] as const;

export type MessageKind = (typeof messageKinds)[number];
export type UiStructuredMessageSource = Readonly<Record<string, string>>;
export type UiMessageSource = string | UiStructuredMessageSource;

export interface UiMessageDescriptor {
  namespace: string;
  key: string;
  source: UiMessageSource;
  description: string;
  placeholders: readonly string[];
  messageKind: MessageKind;
  protectedTerms: readonly string[];
}

export const canonicalEnglishCatalog = {
  common: {
    productName: {
      namespace: "common",
      key: "productName",
      source: "Vico Forum",
      description: "The product name shown above the page heading.",
      placeholders: [],
      messageKind: "plain",
      protectedTerms: ["Vico Forum"],
    },
    heading: {
      namespace: "common",
      key: "heading",
      source: "Translation foundation",
      description: "Heading of the Stage 1 landing page.",
      placeholders: [],
      messageKind: "plain",
      protectedTerms: [],
    },
    stageSummary: {
      namespace: "common",
      key: "stageSummary",
      source: "Stage 1 establishes locale-aware routing and synchronized UI translation.",
      description: "Short description of the completed Stage 1 foundation.",
      placeholders: [],
      messageKind: "plain",
      protectedTerms: ["Stage 1"],
    },
    forumTagline: message("forumTagline", "Questions, discussions, and practical answers", "Forum header tagline."),
    primaryNavigation: message("primaryNavigation", "Primary navigation", "Accessible label for the forum primary navigation."),
    skipToContent: message("skipToContent", "Skip to content", "Keyboard shortcut link that moves focus past the shared forum header."),
    themeLabel: message("themeLabel", "Theme", "Theme control label before the client preference is resolved."),
    lightTheme: message("lightTheme", "Light", "Compact label for switching to the light theme."),
    darkTheme: message("darkTheme", "Dark", "Compact label for switching to the dark theme."),
    switchToLightTheme: message("switchToLightTheme", "Switch to light theme", "Accessible label for switching from dark to light theme."),
    switchToDarkTheme: message("switchToDarkTheme", "Switch to dark theme", "Accessible label for switching from light to dark theme."),
    searchForum: message("searchForum", "Search the forum", "Global forum search entry point."),
    searchEyebrow: message("searchEyebrow", "Discovery", "Eyebrow above the forum search page heading."),
    searchHeading: message("searchHeading", "Search", "Heading of the global forum search page."),
    searchIntro: message("searchIntro", "Search current topic titles, messages, and technology tags.", "Short explanation of the forum search scope."),
    searchInputLabel: message("searchInputLabel", "Search query", "Label for the global forum search input."),
    searchInputPlaceholder: message("searchInputPlaceholder", "Type words from a topic, message, or tag", "Placeholder for the global forum search input."),
    searchSubmit: message("searchSubmit", "Search", "Submit action for the global forum search form."),
    searchPrompt: message("searchPrompt", "Enter a search query to find forum topics.", "Initial search-page guidance before a query is submitted."),
    searchTooLong: message("searchTooLong", "Search queries can be up to 200 characters.", "Validation message for an overlong search query."),
    searchNoResults: message("searchNoResults", "No topics found for “{{query}}”.", "Empty-state message when a forum search has no matching topics.", ["query"]),
    searchResultsHeading: message("searchResultsHeading", "Results for “{{query}}”", "Heading above forum search results.", ["query"]),
    searchResultCount: pluralMessage(
      "searchResultCount",
      { one: "{{count}} result", other: "{{count}} results" },
      "Number of topics returned by forum search.",
      ["count"],
    ),
    notifications: message("notifications", "Notifications", "Authenticated notification entry point."),
    notificationsUnreadLabel: message("notificationsUnreadLabel", "Notifications, {{count}} unread", "Accessible header notification label including the unread count.", ["count"]),
    notificationIntro: message("notificationIntro", "Replies to your topics and messages.", "Short explanation of the authenticated notification inbox."),
    notificationEmpty: message("notificationEmpty", "You have no notifications.", "Empty-state message for the authenticated notification inbox."),
    notificationReplyBy: message("notificationReplyBy", "Reply from {{actor}}", "Notification summary identifying the reply author.", ["actor"]),
    notificationUnread: message("notificationUnread", "Unread", "Status label for an unread reply notification."),
    notificationRead: message("notificationRead", "Read", "Status label for a read reply notification."),
    notificationOpen: message("notificationOpen", "Open reply", "Action that marks a reply notification read and opens the referenced reply."),
    forumHomeNav: message("forumHomeNav", "Home", "Primary navigation link to the forum homepage."),
    unansweredNav: message("unansweredNav", "Unanswered", "Homepage navigation entry for topics without an answer."),
    unansweredEyebrow: message("unansweredEyebrow", "Discovery", "Eyebrow above the Unanswered topics page heading."),
    unansweredHeading: message("unansweredHeading", "Unanswered topics", "Heading of the forum-wide Unanswered topics page."),
    unansweredIntro: message("unansweredIntro", "Topics that are not solved and have not received a reply yet.", "Short explanation of the Unanswered topics filter."),
    unansweredEmpty: message("unansweredEmpty", "There are no unanswered topics right now.", "Empty-state message for the Unanswered topics page."),
    unansweredNoReplies: message("unansweredNoReplies", "No replies yet", "Status label for a topic that has only its initial post."),
    tagsNav: message("tagsNav", "Tags", "Homepage navigation entry for technology tags."),
    tagsEyebrow: message("tagsEyebrow", "Discovery", "Eyebrow above the Tags discovery page heading."),
    tagsHeading: message("tagsHeading", "Technology tags", "Heading of the forum-wide technology Tags page."),
    tagsIntro: message("tagsIntro", "Browse forum topics by technology tag.", "Short explanation of the Tags discovery page."),
    tagsEmpty: message("tagsEmpty", "There are no tags yet.", "Empty-state message for the Tags discovery page."),
    tagTopicsHeading: message("tagTopicsHeading", "Topics tagged {{tag}}", "Accessible heading for topics filtered by one tag.", ["tag"]),
    tagTopicsIntro: message("tagTopicsIntro", "Topics using this tag.", "Short explanation above topics filtered by one tag."),
    tagTopicsEmpty: message("tagTopicsEmpty", "There are no topics with this tag.", "Empty-state message for a tag with no topics."),
    tagTopicCount: pluralMessage(
      "tagTopicCount",
      { one: "{{count}} topic", other: "{{count}} topics" },
      "Number of topics using a technology tag.",
      ["count"],
    ),
    topicTagsLabel: message("topicTagsLabel", "Tags", "Accessible label for topic technology tags."),
    topicTagsInputLabel: message("topicTagsInputLabel", "Tags", "Label for free-form tags on the create-topic form."),
    topicTagsInputHelp: message("topicTagsInputHelp", "Separate tags with commas, for example: TypeScript, Cloudflare, PostgreSQL.", "Help text for free-form topic tags.", [], ["TypeScript", "Cloudflare", "PostgreSQL"]),
    popularNav: message("popularNav", "Popular", "Homepage navigation entry for activity-ranked popular topics."),
    popularEyebrow: message("popularEyebrow", "Discovery", "Eyebrow above the Popular topics page heading."),
    popularHeading: message("popularHeading", "Popular topics", "Heading of the activity-ranked Popular topics page."),
    popularIntro: message("popularIntro", "Topics with the most message activity in each recent period.", "Short explanation of how Popular topics are ranked."),
    popularPeriod24h: message("popularPeriod24h", "24 hours", "Label for the Popular activity period covering the latest 24 hours."),
    popularPeriod7d: message("popularPeriod7d", "7 days", "Label for the Popular activity period covering the latest 7 days."),
    popularPeriod30d: message("popularPeriod30d", "30 days", "Label for the Popular activity period covering the latest 30 days."),
    popularEmpty: message("popularEmpty", "No topic activity in this period.", "Empty-state message for one Popular activity period."),
    unreadNav: message("unreadNav", "Unread", "Authenticated-only homepage navigation entry for unread topics."),
    unreadEyebrow: message("unreadEyebrow", "Discovery", "Eyebrow above the authenticated Unread topics page heading."),
    unreadHeading: message("unreadHeading", "Unread topics", "Heading of the authenticated Unread topics page."),
    unreadExistingHeading: message("unreadExistingHeading", "Unread", "Heading above topics with unread messages on the authenticated Unread page."),
    unreadNewHeading: message("unreadNewHeading", "New", "Heading above topics the current user has never opened on the authenticated Unread page."),
    unreadIntro: message("unreadIntro", "New topics and topics with messages you have not read yet.", "Short explanation of the authenticated Unread topics page."),
    unreadEmpty: message("unreadEmpty", "You have no unread topics.", "Empty-state message for the authenticated Unread topics page."),
    unreadNew: message("unreadNew", "New", "Status label for a topic the current user has never opened."),
    readStateRead: message("readStateRead", "Read", "Status label for a topic whose current messages have been read."),
    unreadCount: pluralMessage(
      "unreadCount",
      { one: "{{count}} unread message", other: "{{count}} unread messages" },
      "Number of unread messages after the current user's topic read marker.",
      ["count"],
    ),
    enterForumSection: message("enterForumSection", "Open {{section}}", "Accessible label for the vertical homepage category action.", ["section"]),
    forumDiscoveryDevelopmentStatus: message("forumDiscoveryDevelopmentStatus", "{{section}}: development status", "Accessible label while the homepage category action temporarily routes to the shared development page.", ["section"]),
    footerNavigation: message("footerNavigation", "Footer navigation", "Accessible label for the forum footer navigation."),
    rulesNav: message("rulesNav", "Rules", "Footer link to forum rules."),
    helpNav: message("helpNav", "Help", "Footer link to help."),
    aboutVicoNav: message("aboutVicoNav", "About Vico", "Footer link to product information.", [], ["Vico"]),
    feedbackNav: message("feedbackNav", "Feedback", "Footer link to feedback."),
    privacyNav: message("privacyNav", "Privacy", "Footer link to privacy information."),
    homeForumSectionsHeading: message("homeForumSectionsHeading", "Forum sections", "Heading above the primary forum blocks on the homepage."),
    pinnedHeading: message("pinnedHeading", "Pinned", "Heading for pinned topics in a homepage forum block."),
    latestTopicsHeading: message("latestTopicsHeading", "Latest topics", "Heading for latest topics in a homepage forum block."),
    homepageSectionFallbackDescription: message("homepageSectionFallbackDescription", "Sections, discussions, and practical answers in this area.", "Fallback description for a database-backed homepage category."),
    homepagePinnedEmpty: message("homepagePinnedEmpty", "No pinned topics yet.", "Empty state for a homepage category with no persisted pinned topics."),
    homepageLatestEmpty: message("homepageLatestEmpty", "No topics yet.", "Empty latest-topic area on a real homepage category."),
    homepageExpand: message("homepageExpand", "Show more topics", "Accessible label for expanding a homepage forum block."),
    homepageCollapse: message("homepageCollapse", "Show fewer topics", "Accessible label for collapsing a homepage forum block."),
    forumStatisticsHeading: message("forumStatisticsHeading", "Forum statistics", "Heading for aggregate homepage forum statistics."),
    whosOnlineHeading: message("whosOnlineHeading", "Who's online", "Heading for the homepage online-presence area."),
    onlinePresencePending: message("onlinePresencePending", "Online presence is still under development.", "Truthful placeholder while online presence is not implemented."),
    viewDevelopmentStatus: message("viewDevelopmentStatus", "View development status", "Link to the shared under-development status page."),
    underDevelopmentEyebrow: message("underDevelopmentEyebrow", "Pre-release", "Eyebrow for the shared under-development page."),
    underDevelopmentHeading: message("underDevelopmentHeading", "Under development", "Heading for the shared unfinished-function page."),
    underDevelopmentIntro: message("underDevelopmentIntro", "This page tracks approved Vico Forum functions that are not finished yet. Entry points stay visible during owner-only pre-release instead of pretending to work.", "Explanation of the shared pre-release under-development page.", [], ["Vico Forum"]),
    underDevelopmentRequested: message("underDevelopmentRequested", "{{feature}} is not finished yet.", "Status message for the unfinished feature that led to this page.", ["feature"]),
    underDevelopmentRemainingHeading: message("underDevelopmentRemainingHeading", "Still in development", "Heading above the current unfinished-feature checklist."),
    underDevelopmentBackToForum: message("underDevelopmentBackToForum", "Back to the forum", "Return link from the under-development page."),
    underDevelopmentFeatureSearch: message("underDevelopmentFeatureSearch", "Global forum search", "Unfinished feature label."),
    underDevelopmentFeatureNotifications: message("underDevelopmentFeatureNotifications", "Notifications", "Unfinished feature label."),
    underDevelopmentFeatureRegistration: message("underDevelopmentFeatureRegistration", "Account registration", "Unfinished feature label."),
    underDevelopmentFeaturePinnedTopics: message("underDevelopmentFeaturePinnedTopics", "Pinned-topic management", "Unfinished feature label."),
    underDevelopmentFeatureUnread: message("underDevelopmentFeatureUnread", "Unread/new state and jump to first unread", "Unfinished feature label."),
    underDevelopmentFeatureDrafts: message("underDevelopmentFeatureDrafts", "Drafts and autosave", "Unfinished feature label."),
    underDevelopmentFeatureProfiles: message("underDevelopmentFeatureProfiles", "Forum user profiles", "Unfinished feature label."),
    underDevelopmentFeatureTechnologyTags: message("underDevelopmentFeatureTechnologyTags", "Technology tags", "Unfinished feature label."),
    underDevelopmentFeatureUnansweredFilter: message("underDevelopmentFeatureUnansweredFilter", "Unanswered filter", "Unfinished feature label."),
    underDevelopmentFeaturePopular: message("underDevelopmentFeaturePopular", "Popular topics by activity period", "Unfinished feature label."),
    underDevelopmentFeatureForumDiscovery: message("underDevelopmentFeatureForumDiscovery", "Forum category and section presentation", "Unfinished forum discovery presentation label."),
    underDevelopmentFeatureMessageLinks: message("underDevelopmentFeatureMessageLinks", "Permanent message links and copy-link actions", "Unfinished feature label."),
    underDevelopmentFeatureReplyQuote: message("underDevelopmentFeatureReplyQuote", "Reply and quote relationships", "Unfinished feature label."),
    underDevelopmentFeatureEditor: message("underDevelopmentFeatureEditor", "Full editor and code tooling", "Unfinished feature label."),
    underDevelopmentFeatureOnlinePresence: message("underDevelopmentFeatureOnlinePresence", "Who's online", "Unfinished feature label."),
    underDevelopmentFeatureRules: message("underDevelopmentFeatureRules", "Forum rules page", "Unfinished content destination label."),
    underDevelopmentFeatureHelp: message("underDevelopmentFeatureHelp", "Help page", "Unfinished content destination label."),
    underDevelopmentFeatureAbout: message("underDevelopmentFeatureAbout", "About Vico", "Unfinished content destination label.", [], ["Vico"]),
    underDevelopmentFeatureFeedback: message("underDevelopmentFeatureFeedback", "Feedback", "Unfinished content destination label."),
    underDevelopmentFeaturePrivacy: message("underDevelopmentFeaturePrivacy", "Privacy page", "Unfinished content destination label."),
    signInGoogle: message("signInGoogle", "Sign in", "Google-backed sign-in button in the forum header."),
    signUp: message("signUp", "Sign up", "Future registration entry point in the forum header."),
    signOut: message("signOut", "Sign out", "Sign-out button in the forum header."),
    authPending: message("authPending", "Please wait…", "Pending label while an authentication request is running."),
    authError: message("authError", "Authentication failed. Please try again.", "Safe error shown when an authentication request fails."),
    forumIndex: message("forumIndex", "Forum index", "Link and eyebrow for the forum index."),
    categoriesHeading: message("categoriesHeading", "Categories", "Heading above the public category list."),
    categoriesIntro: message("categoriesIntro", "Browse the forum by category and section.", "Introduction to the forum index."),
    categoriesEmpty: message("categoriesEmpty", "There are no categories yet.", "Empty category list message."),
    sectionsEmpty: message("sectionsEmpty", "There are no sections in this category yet.", "Empty section list message."),
    topicsEmpty: message("topicsEmpty", "There are no topics in this section yet.", "Empty topic list message."),
    postsEmpty: message("postsEmpty", "There are no messages in this topic yet.", "Empty post list message."),
    breadcrumbsLabel: message("breadcrumbsLabel", "Breadcrumbs", "Accessible label for forum breadcrumbs."),
    categoryLabel: message("categoryLabel", "Category", "Category page type label."),
    sectionLabel: message("sectionLabel", "Section", "Section page type label."),
    topicLabel: message("topicLabel", "Topic", "Topic page type label."),
    topicsHeading: message("topicsHeading", "Topics", "Accessible heading for the topic table."),
    topicColumn: message("topicColumn", "Topic", "Topic table title column."),
    postsColumn: message("postsColumn", "Messages", "Topic table message-count column."),
    sectionCount: pluralMessage(
      "sectionCount",
      { one: "{{count}} section", other: "{{count}} sections" },
      "Number of sections in a category.",
      ["count"],
    ),
    topicCount: pluralMessage(
      "topicCount",
      { one: "{{count}} topic", other: "{{count}} topics" },
      "Number of topics in a section.",
      ["count"],
    ),
    messageCount: pluralMessage(
      "messageCount",
      { one: "{{count}} message", other: "{{count}} messages" },
      "Number of messages in a section.",
      ["count"],
    ),
    startedBy: message("startedBy", "Started by {{author}}", "Name of the topic author.", ["author"]),
    postNumber: message("postNumber", "Message #{{number}}", "Sequential message number.", ["number"]),
    copyMessageLink: message("copyMessageLink", "Copy link", "Action that copies a permanent link to a forum message."),
    copyMessageLinkFor: message("copyMessageLinkFor", "Copy link to {{message}}", "Accessible label for the action that copies a permanent forum message link.", ["message"]),
    messageLinkCopied: message("messageLinkCopied", "Copied", "Confirmation after a permanent forum message link is copied."),
    messageLinkCopyFailed: message("messageLinkCopyFailed", "Could not copy link.", "Failure feedback when a permanent forum message link cannot be copied."),
    messageActions: message("messageActions", "Actions", "Compact label for the mobile message actions menu."),
    replyToMessage: message("replyToMessage", "Reply", "Action that targets a reply at one forum message."),
    replyToMessageNumberCompact: message("replyToMessageNumberCompact", "Reply to #{{number}}", "Compact parent-message link used in the mobile message header.", ["number"]),
    directRepliesCompact: message("directRepliesCompact", "Replies", "Compact label for direct-reply links in a mobile message footer."),
    quoteSelectedText: message("quoteSelectedText", "Quote", "Action that inserts selected message text into the reply editor as a Markdown blockquote."),
    replyToMessageNumber: message("replyToMessageNumber", "Reply to Message #{{number}}", "Link from a direct reply to its parent message.", ["number"]),
    directReplies: message("directReplies", "Direct replies", "Label for links to messages that directly reply to this message."),
    replyingToMessage: message("replyingToMessage", "Replying to Message #{{number}}", "Reply editor banner showing the currently targeted parent message.", ["number"]),
    clearReplyTarget: message("clearReplyTarget", "Reply to topic instead", "Action that clears the targeted parent message from the reply editor."),
    quoteSelectionRequired: message("quoteSelectionRequired", "Select text in this message to quote it.", "Guidance shown when Quote is used without a valid text selection inside that message."),
    originalQuestion: message("originalQuestion", "Original question", "Label for the first message in a topic."),
    systemStateEyebrow: message("systemStateEyebrow", "System state", "Compact eyebrow for route error/system-state presentation."),
    routeBackToForum: message("routeBackToForum", "Back to forum", "Safe navigation action from a route error state."),
    routeUnauthenticatedHeading: message("routeUnauthenticatedHeading", "Sign in required", "Heading for a protected route shown without an authenticated session."),
    routeUnauthenticatedBody: message("routeUnauthenticatedBody", "Sign in to access this page.", "Explanation for a protected route shown without an authenticated session."),
    routeForbiddenHeading: message("routeForbiddenHeading", "Access denied", "Heading for an authenticated user without the required permission."),
    routeForbiddenBody: message("routeForbiddenBody", "You do not have permission to open this page.", "Explanation for an authenticated user without the required permission."),
    routeUnavailableHeading: message("routeUnavailableHeading", "Temporarily unavailable", "Heading for a controlled temporary dependency outage."),
    routeUnavailableBody: message("routeUnavailableBody", "This part of Vico Forum is temporarily unavailable. Please try again later.", "Explanation for a controlled temporary dependency outage."),
    forumNotFoundHeading: message("forumNotFoundHeading", "Forum page not found", "Forum not-found heading."),
    forumNotFoundBody: message("forumNotFoundBody", "The category, section, or topic does not exist.", "Forum not-found explanation."),
    forumErrorHeading: message("forumErrorHeading", "The forum could not be loaded", "Forum read error heading."),
    forumErrorBody: message("forumErrorBody", "Please try again later.", "Forum read error explanation."),
    authoringLabel: message("authoringLabel", "Write", "Compact eyebrow above forum authoring forms."),
    createTopicHeading: message("createTopicHeading", "Create a new topic", "Heading above the authenticated topic form."),
    createTopicHelp: message("createTopicHelp", "Start a focused discussion in this section.", "Short guidance beside the create-topic heading."),
    topicTitleLabel: message("topicTitleLabel", "Topic title", "Label for a new topic title."),
    topicTitleHelp: message("topicTitleHelp", "Use a clear, specific title.", "Help text below the topic-title field."),
    initialPostLabel: message("initialPostLabel", "First message", "Label for a new topic's first message."),
    createTopicSubmit: message("createTopicSubmit", "Create topic", "Submit button for a new topic."),
    createTopicSubmitting: message("createTopicSubmitting", "Creating topic…", "Pending label while a new topic is being submitted."),
    replyHeading: message("replyHeading", "Add a reply", "Heading above the authenticated reply form."),
    replyHelp: message("replyHelp", "Add useful context, an answer, or a follow-up.", "Short guidance beside the reply heading."),
    replyBodyLabel: message("replyBodyLabel", "Reply", "Label for a reply body."),
    replySubmit: message("replySubmit", "Post reply", "Submit button for a reply."),
    replySubmitting: message("replySubmitting", "Posting reply…", "Pending label while a reply is being submitted."),
    messageBodyHelp: message("messageBodyHelp", "Markdown and fenced code blocks are supported.", "Help text below forum message textareas."),
    authoringRequiredHint: message("authoringRequiredHint", "All fields are required.", "Required-field hint in forum authoring forms."),
    solved: message("solved", "Solved", "Solved topic status."),
    markSolved: message("markSolved", "Mark as solved", "Action for the topic author to mark a topic solved."),
    bestAnswer: message("bestAnswer", "Best answer", "Label on the selected best answer."),
    selectBestAnswer: message("selectBestAnswer", "Select as best answer", "Action for the topic author to select a post."),
    goToSolution: message("goToSolution", "Go to solution", "Link from the topic heading to the best answer."),
    topicTools: message("topicTools", "Topic tools", "Progressive-disclosure label for secondary topic management controls."),
    pinTopic: message("pinTopic", "Pin topic", "Action for authorized users to pin the current topic."),
    unpinTopic: message("unpinTopic", "Unpin topic", "Action for authorized users to remove the current topic pin."),
    messageTools: message("messageTools", "Message tools", "Progressive-disclosure label for secondary message management controls."),
    automaticTranslation: message("automaticTranslation", "Automatic translation", "Marker for a machine-translated forum content unit."),
    manualTranslation: message("manualTranslation", "Manual translation", "Marker for a persisted manual forum content translation."),
    showOriginal: message("showOriginal", "Show original", "Control that reveals the original forum content beside a translation."),
    hideOriginal: message("hideOriginal", "Hide original", "Control that collapses the revealed original forum content beneath a translation."),
    showTranslation: message("showTranslation", "Show translation", "Control that returns focus to the translated forum content."),
    translationRequesting: message("translationRequesting", "Requesting translation…", "Accessible pending feedback while a content translation request is being submitted."),
    translationPending: message("translationPending", "Translation queued.", "Content translation task is queued and waiting to run."),
    translationProcessing: message("translationProcessing", "Translation is being prepared.", "Content translation task is currently processing."),
    translationConverging: message("translationConverging", "Translation is becoming available.", "Read-only convergence feedback when task completion is newer than the independently read presentation."),
    translationDeferred: message("translationDeferred", "Translation is temporarily deferred.", "Content translation task is durably deferred."),
    translationDeferredFor: message("translationDeferredFor", "Translation is deferred. Try again in about {{seconds}} seconds.", "Deferred content translation feedback with bounded retry timing.", ["seconds"]),
    translationFailed: message("translationFailed", "Translation could not be completed.", "Terminal content translation failure feedback."),
    translationUnavailable: message("translationUnavailable", "Translation is temporarily unavailable.", "Temporary generation or status-storage availability feedback."),
    translationExplicitRequired: message("translationExplicitRequired", "This long message requires an explicit translation request.", "Long post body requires an explicit user action before translation planning."),
    translationExplicitAction: message("translationExplicitAction", "Translate this message", "Explicit translation action for a long post body."),
    translationCurrent: message("translationCurrent", "Translation is current.", "Exact-current translated content is already displayed."),
    translationRequestChanged: message("translationRequestChanged", "The content or translation state changed. Review the current page.", "Safe feedback when a generation request becomes ineligible or stale."),
    translationRetryAfter: message("translationRetryAfter", "Translation requests are limited. Try again in {{seconds}} seconds.", "Bounded request-budget feedback without exposing quota internals.", ["seconds"]),
    sourceLocaleCurrent: message("sourceLocaleCurrent", "Source language: {{locale}}", "Current source-language metadata for forum content.", ["locale"]),
    sourceLocaleCorrectionInput: message("sourceLocaleCorrectionInput", "Correct source language", "Label for the source-language correction input."),
    sourceLocaleCorrectionSubmit: message("sourceLocaleCorrectionSubmit", "Correct language", "Submit action for source-language metadata correction."),
    sourceLocaleCorrectionError_invalid: message("sourceLocaleCorrectionError_invalid", "Enter a valid BCP-47 source language.", "Invalid source-language correction."),
    sourceLocaleCorrectionError_unauthenticated: message("sourceLocaleCorrectionError_unauthenticated", "Sign in to correct the source language.", "Unauthenticated source-language correction."),
    sourceLocaleCorrectionError_origin: message("sourceLocaleCorrectionError_origin", "This correction request could not be verified.", "Origin failure for source-language correction."),
    sourceLocaleCorrectionError_forbidden: message("sourceLocaleCorrectionError_forbidden", "You cannot correct the source language for this content.", "Forbidden source-language correction."),
    sourceLocaleCorrectionError_notFound: message("sourceLocaleCorrectionError_notFound", "The content to correct no longer exists.", "Missing source-language correction target."),
    sourceLocaleCorrectionError_conflict: message("sourceLocaleCorrectionError_conflict", "The content changed before the source language could be corrected. Reload and try again.", "Stale source-language correction."),
    sourceLocaleCorrectionError_unavailable: message("sourceLocaleCorrectionError_unavailable", "The source language could not be corrected. Please try again later.", "Temporary source-language correction storage failure."),
    forumWriteError_invalid: message("forumWriteError_invalid", "Enter all required fields.", "Forum mutation validation error."),
    forumWriteError_unauthenticated: message("forumWriteError_unauthenticated", "Sign in to continue.", "Forum mutation authentication error."),
    forumWriteError_origin: message("forumWriteError_origin", "This request could not be verified.", "Forum mutation origin error."),
    forumWriteError_forbidden: message("forumWriteError_forbidden", "Only the topic author can change its solution.", "Forum solution authorization error."),
    forumWriteError_conflict: message("forumWriteError_conflict", "That solution cannot be selected for this topic.", "Forum solution state conflict."),
    forumWriteError_notFound: message("forumWriteError_notFound", "The target section or topic no longer exists.", "Forum mutation missing target error."),
    forumWriteError_rateLimited: message("forumWriteError_rateLimited", "Please wait a few seconds before posting again.", "Forum mutation rate limit error."),
    forumWriteError_unavailable: message("forumWriteError_unavailable", "Your message could not be saved. Please try again.", "Forum mutation storage error."),
    authorizationNav: message("authorizationNav", "Authorization", "Link to authorization management."),
    authorizationHeading: message("authorizationHeading", "Authorization management", "Authorization management page heading."),
    rolesHeading: message("rolesHeading", "Roles", "Role management heading."),
    usersHeading: message("usersHeading", "Users", "User authorization heading."),
    roleSlug: message("roleSlug", "Role slug", "Role slug field label."),
    displayName: message("displayName", "Display name", "Role display-name field label."),
    createRole: message("createRole", "Create custom role", "Create-role action."),
    save: message("save", "Save", "Generic save action."),
    deleteRole: message("deleteRole", "Delete role", "Delete-role action."),
    builtInRole: message("builtInRole", "Built-in", "Built-in role marker."),
    permissionsHeading: message("permissionsHeading", "Permissions", "Permissions heading."),
    effectivePermissions: message("effectivePermissions", "Effective permissions", "Effective permissions heading."),
    assignedRole: message("assignedRole", "Assigned role", "Assigned role field label."),
    defaultRole: message("defaultRole", "Default role", "Default role marker."),
    overrideInherit: message("overrideInherit", "Inherit", "Inherited permission option."),
    overrideAllow: message("overrideAllow", "Allow", "Allowed permission option."),
    overrideDeny: message("overrideDeny", "Deny", "Denied permission option."),
    authorizationSaved: message("authorizationSaved", "Authorization was updated.", "Successful authorization mutation message."),
    authorizationError_invalid: message("authorizationError_invalid", "Check the submitted values.", "Invalid authorization mutation."),
    authorizationError_forbidden: message("authorizationError_forbidden", "You cannot manage authorization.", "Forbidden authorization mutation."),
    authorizationError_notFound: message("authorizationError_notFound", "The selected role or user no longer exists.", "Missing authorization entity."),
    authorizationError_conflict: message("authorizationError_conflict", "This change would cause a lockout or the role is assigned.", "Authorization conflict."),
    authorizationError_unavailable: message("authorizationError_unavailable", "Authorization is temporarily unavailable.", "Authorization infrastructure error."),
  },
} as const satisfies Record<string, Record<string, UiMessageDescriptor>>;

function message<const Key extends string, const Source extends string>(
  key: Key,
  source: Source,
  description: string,
  placeholders: readonly string[] = [],
  protectedTerms: readonly string[] = [],
) {
  return {
    namespace: "common",
    key,
    source,
    description,
    placeholders,
    messageKind: placeholders.length === 0 ? "plain" : "interpolation",
    protectedTerms,
  } as const satisfies UiMessageDescriptor;
}

function pluralMessage<const Key extends string, const Source extends UiStructuredMessageSource>(
  key: Key,
  source: Source,
  description: string,
  placeholders: readonly string[],
  protectedTerms: readonly string[] = [],
) {
  return {
    namespace: "common",
    key,
    source,
    description,
    placeholders,
    messageKind: "plural",
    protectedTerms,
  } as const satisfies UiMessageDescriptor;
}

export type UiNamespace = keyof typeof canonicalEnglishCatalog;
export type UiKey<N extends UiNamespace> = keyof (typeof canonicalEnglishCatalog)[N] & string;
type DescriptorSource<T> = T extends { readonly source: infer Source }
  ? Source extends string ? Source : string
  : never;
export type CanonicalResourceShape = {
  [N in UiNamespace]: {
    [K in UiKey<N>]: DescriptorSource<(typeof canonicalEnglishCatalog)[N][K]>;
  };
};

export function catalogDescriptors(): UiMessageDescriptor[] {
  return Object.values(canonicalEnglishCatalog).flatMap((namespace) =>
    Object.values(namespace) as UiMessageDescriptor[],
  );
}
