export const messageKinds = ["plain", "interpolation", "plural", "contextual/select", "rich"] as const;

export type MessageKind = (typeof messageKinds)[number];
export type UiStructuredMessageSource = Readonly<Record<string, string>>;
export type UiMessageSource = string | UiStructuredMessageSource;

export interface UiMessageDescriptor {
  namespace: string;
  key: string;
  source: UiMessageSource;
  description: string;
  placeholders: readonly string[];
  messageKind: MessageKind;
  protectedTerms: readonly string[];
}

export const canonicalEnglishCatalog = {
  common: {
    profileHeading: message("profileHeading", "Forum profile", "Forum profile: profileHeading."),
    profileEdit: message("profileEdit", "Edit profile", "Forum profile: profileEdit."),
    profileJoined: message("profileJoined", "Joined", "Forum profile: profileJoined."),
    profileMessages: message("profileMessages", "Messages", "Forum profile: profileMessages."),
    profileBestAnswers: message("profileBestAnswers", "Best answers", "Forum profile: profileBestAnswers."),
    profileBio: message("profileBio", "About", "Forum profile: profileBio."),
    profileNoBio: message("profileNoBio", "No description yet.", "Forum profile: profileNoBio."),
    profileLinks: message("profileLinks", "Profile links", "Forum profile: profileLinks."),
    profileWebsite: message("profileWebsite", "Website", "Forum profile: profileWebsite."),
    profileBioHint: message("profileBioHint", "Up to 500 characters. This description is public.", "Forum profile: profileBioHint."),
    profileGithubHint: message("profileGithubHint", "A public GitHub profile link. Optional.", "Forum profile: profileGithubHint."),
    profileWebsiteHint: message("profileWebsiteHint", "Use a full HTTP or HTTPS link. Optional.", "Forum profile: profileWebsiteHint."),
    profileSave: message("profileSave", "Save profile", "Forum profile: profileSave."),
    profileSaving: message("profileSaving", "Saving…", "Forum profile: profileSaving."),
    profileCancel: message("profileCancel", "Cancel", "Forum profile: profileCancel."),
    profileSaved: message("profileSaved", "Profile saved.", "Forum profile: profileSaved."),
    profileInvalid: message("profileInvalid", "Use up to 500 characters and valid public links. GitHub must link to a user profile.", "Forum profile: profileInvalid."),
    profileRoleUser: message("profileRoleUser", "Member", "Forum profile: profileRoleUser."),
    profileRoleModerator: message("profileRoleModerator", "Moderator", "Forum profile: profileRoleModerator."),
    profileRoleAdmin: message("profileRoleAdmin", "Administrator", "Forum profile: profileRoleAdmin."),
    profileError_unauthenticated: message("profileError_unauthenticated", "Sign in to edit your profile.", "Forum profile: profileError_unauthenticated."),
    profileError_origin: message("profileError_origin", "This request could not be verified.", "Forum profile: profileError_origin."),
    profileError_forbidden: message("profileError_forbidden", "You can edit only your own profile.", "Forum profile: profileError_forbidden."),
    profileError_notFound: message("profileError_notFound", "This profile no longer exists.", "Forum profile: profileError_notFound."),
    profileError_unavailable: message("profileError_unavailable", "Your profile could not be saved. Try again.", "Forum profile: profileError_unavailable."),

    productName: {
      namespace: "common",
      key: "productName",
      source: "Vico Forum",
      description: "The product name shown above the page heading.",
      placeholders: [],
      messageKind: "plain",
      protectedTerms: ["Vico Forum"],
    },
    heading: {
      namespace: "common",
      key: "heading",
      source: "Translation foundation",
      description: "Heading of the Stage 1 landing page.",
      placeholders: [],
      messageKind: "plain",
      protectedTerms: [],
    },
    stageSummary: {
      namespace: "common",
      key: "stageSummary",
      source: "Stage 1 establishes locale-aware routing and synchronized UI translation.",
      description: "Short description of the completed Stage 1 foundation.",
      placeholders: [],
      messageKind: "plain",
      protectedTerms: ["Stage 1"],
    },
    forumTagline: message("forumTagline", "Questions, discussions, and practical answers", "Forum header tagline."),
    primaryNavigation: message("primaryNavigation", "Primary navigation", "Accessible label for the forum primary navigation."),
    skipToContent: message("skipToContent", "Skip to content", "Keyboard shortcut link that moves focus past the shared forum header."),
    themeLabel: message("themeLabel", "Theme", "Theme control label before the client preference is resolved."),
    lightTheme: message("lightTheme", "Light", "Compact label for switching to the light theme."),
    darkTheme: message("darkTheme", "Dark", "Compact label for switching to the dark theme."),
    switchToLightTheme: message("switchToLightTheme", "Switch to light theme", "Accessible label for switching from dark to light theme."),
    switchToDarkTheme: message("switchToDarkTheme", "Switch to dark theme", "Accessible label for switching from light to dark theme."),
    searchForum: message("searchForum", "Search the forum", "Global forum search entry point."),
    searchEyebrow: message("searchEyebrow", "Discovery", "Eyebrow above the forum search page heading."),
    searchHeading: message("searchHeading", "Search", "Heading of the global forum search page."),
    searchIntro: message("searchIntro", "Search current topic titles, messages, and technology tags.", "Short explanation of the forum search scope."),
    searchInputLabel: message("searchInputLabel", "Search query", "Label for the global forum search input."),
    searchInputPlaceholder: message("searchInputPlaceholder", "Type words from a topic, message, or tag", "Placeholder for the global forum search input."),
    searchSubmit: message("searchSubmit", "Search", "Submit action for the global forum search form."),
    searchPrompt: message("searchPrompt", "Enter a search query to find forum topics.", "Initial search-page guidance before a query is submitted."),
    searchTooLong: message("searchTooLong", "Search queries can be up to 200 characters.", "Validation message for an overlong search query."),
    searchNoResults: message("searchNoResults", "No topics found for “{{query}}”.", "Empty-state message when a forum search has no matching topics.", ["query"]),
    searchResultsHeading: message("searchResultsHeading", "Results for “{{query}}”", "Heading above forum search results.", ["query"]),
    searchResultCount: pluralMessage(
      "searchResultCount",
      { one: "{{count}} result", other: "{{count}} results" },
      "Number of topics returned by forum search.",
      ["count"],
    ),
    notifications: message("notifications", "Notifications", "Authenticated notification entry point."),
    notificationsUnreadLabel: message("notificationsUnreadLabel", "Notifications, {{count}} unread", "Accessible header notification label including the unread count.", ["count"]),
    notificationIntro: message("notificationIntro", "Replies to your topics and messages.", "Short explanation of the authenticated notification inbox."),
    notificationEmpty: message("notificationEmpty", "You have no notifications.", "Empty-state message for the authenticated notification inbox."),
    notificationReplyBy: message("notificationReplyBy", "Reply from {{actor}}", "Notification summary identifying the reply author.", ["actor"]),
    notificationUnread: message("notificationUnread", "Unread", "Status label for an unread reply notification."),
    notificationRead: message("notificationRead", "Read", "Status label for a read reply notification."),
    notificationOpen: message("notificationOpen", "Open reply", "Action that marks a reply notification read and opens the referenced reply."),
    forumHomeNav: message("forumHomeNav", "Home", "Primary navigation link to the forum homepage."),
    helpSolutionsHeading: message("helpSolutionsHeading", "Help & solutions", "Heading for the dedicated Help & solutions Q&A page."),
    helpSolutionsIntro: message("helpSolutionsIntro", "Technical questions, troubleshooting, and practical solutions from the community.", "Short introduction to the Help & solutions Q&A page."),
    helpSolutionsAllMode: message("helpSolutionsAllMode", "All", "Label for the first Help & solutions question mode showing every question."),
    helpSolutionsAllHeading: message("helpSolutionsAllHeading", "All questions", "Heading above the unfiltered Help & solutions question list."),
    helpSolutionsNeedsHelpMode: message("helpSolutionsNeedsHelpMode", "Needs help", "Label for the Help & solutions mode showing questions that are not solved."),
    helpSolutionsNeedsHelpHeading: message("helpSolutionsNeedsHelpHeading", "Questions needing help", "Heading above unsolved Help & solutions questions."),
    helpSolutionsNeedsHelpEmpty: message("helpSolutionsNeedsHelpEmpty", "There are no questions needing help right now.", "Empty state for the unsolved Help & solutions question list."),
    helpSolutionsWantToHelpMode: message("helpSolutionsWantToHelpMode", "Want to help", "Label for the authenticated Help & solutions mode showing unsolved questions authored by other users."),
    helpSolutionsWantToHelpHeading: message("helpSolutionsWantToHelpHeading", "Questions you can help with", "Heading above unsolved Help & solutions questions authored by other users."),
    helpSolutionsWantToHelpEmpty: message("helpSolutionsWantToHelpEmpty", "There are no open questions from other users right now.", "Empty state for the authenticated Help & solutions mode showing unsolved questions authored by other users."),
    helpSolutionsForMeMode: message("helpSolutionsForMeMode", "For me", "Label for the authenticated Help & solutions mode ranked by tags from the user's existing participation."),
    helpSolutionsForMeHeading: message("helpSolutionsForMeHeading", "Questions for you", "Heading above open Help & solutions questions matching tags from the user's existing participation."),
    helpSolutionsForMeEmpty: message("helpSolutionsForMeEmpty", "There are no matching open questions for you right now.", "Empty state when existing Help & solutions participation yields no matching open questions."),
    helpSolutionsActiveMode: message("helpSolutionsActiveMode", "Active", "Label for the Help & solutions mode showing questions with at least one reply."),
    helpSolutionsActiveHeading: message("helpSolutionsActiveHeading", "Active questions", "Heading above Help & solutions questions that have at least one reply."),
    helpSolutionsActiveEmpty: message("helpSolutionsActiveEmpty", "There are no active questions right now.", "Empty state for Help & solutions questions with at least one reply."),
    helpSolutionsNeedsAttentionMode: message("helpSolutionsNeedsAttentionMode", "Needs attention", "Label for the Help & solutions mode showing unsolved questions with no replies."),
    helpSolutionsNeedsAttentionHeading: message("helpSolutionsNeedsAttentionHeading", "Questions needing attention", "Heading above unsolved Help & solutions questions with no replies."),
    helpSolutionsNeedsAttentionEmpty: message("helpSolutionsNeedsAttentionEmpty", "There are no questions needing attention right now.", "Empty state for unsolved Help & solutions questions with no replies."),
    helpSolutionsMineMode: message("helpSolutionsMineMode", "My questions", "Label for the authenticated Help & solutions mode showing questions authored by the current user."),
    helpSolutionsMineHeading: message("helpSolutionsMineHeading", "My questions", "Heading above the current authenticated user's Help & solutions questions."),
    helpSolutionsMineEmpty: message("helpSolutionsMineEmpty", "You have not asked any questions yet.", "Empty state for the current authenticated user's Help & solutions question list."),
    helpSolutionsSimilarCheck: message("helpSolutionsSimilarCheck", "Check similar questions", "Action that checks for existing similar Help & solutions questions before publishing."),
    helpSolutionsSimilarChecking: message("helpSolutionsSimilarChecking", "Checking…", "Pending label while similar Help & solutions questions are being checked."),
    helpSolutionsSimilarHeading: message("helpSolutionsSimilarHeading", "Similar questions", "Heading above similar existing Help & solutions questions found during authoring."),
    helpSolutionsSimilarIntro: message("helpSolutionsSimilarIntro", "Review these existing questions before posting. You can still publish a new question.", "Guidance shown when similar Help & solutions questions are found."),
    helpSolutionsSimilarEmpty: message("helpSolutionsSimilarEmpty", "No similar questions found.", "Empty state after checking for similar Help & solutions questions."),
    helpSolutionsSimilarInvalid: message("helpSolutionsSimilarInvalid", "Enter a question title up to 200 characters to check for similar questions.", "Validation message for an invalid similar-question check."),
    helpSolutionsSimilarUnavailable: message("helpSolutionsSimilarUnavailable", "Similar-question checking is temporarily unavailable. You can still post your question.", "Unavailable state for the optional similar-question check."),
    helpSolutionsSimilarMatchTitle: message("helpSolutionsSimilarMatchTitle", "Found in title", "Reason shown for a similar Help & solutions question when the strongest match is in the question title."),
    helpSolutionsSimilarMatchTags: message("helpSolutionsSimilarMatchTags", "Found in tags", "Reason shown for a similar Help & solutions question when the strongest match is in technology tags."),
    helpSolutionsSimilarMatchBody: message("helpSolutionsSimilarMatchBody", "Found in discussion", "Reason shown for a similar Help & solutions question when the strongest match is in question or reply content."),
    helpSolutionsAskHeading: message("helpSolutionsAskHeading", "Ask a question", "Heading above the dedicated Help & solutions question form."),
    helpSolutionsAskHelp: message("helpSolutionsAskHelp", "Describe the problem clearly so others can reproduce and solve it.", "Short guidance beside the dedicated Help & solutions question form heading."),
    helpSolutionsQuestionTitleLabel: message("helpSolutionsQuestionTitleLabel", "Question title", "Label for the Help & solutions question title field."),
    helpSolutionsQuestionBodyLabel: message("helpSolutionsQuestionBodyLabel", "Question details", "Label for the Help & solutions question body field."),
    helpSolutionsAskSubmit: message("helpSolutionsAskSubmit", "Ask question", "Submit button for a new Help & solutions question."),
    helpSolutionsAskSubmitting: message("helpSolutionsAskSubmitting", "Posting question…", "Pending label while a Help & solutions question is being submitted."),
    helpSolutionsSolutionsMode: message("helpSolutionsSolutionsMode", "Solutions", "Label for the Help & solutions mode showing solved questions."),
    helpSolutionsSolutionsHeading: message("helpSolutionsSolutionsHeading", "Solved questions", "Heading above solved Help & solutions questions."),
    helpSolutionsSolutionsEmpty: message("helpSolutionsSolutionsEmpty", "There are no solved questions yet.", "Empty state for the solved Help & solutions question list."),
    helpSolutionNeedsReview: message("helpSolutionNeedsReview", "Needs review", "Status label for a solved Help & solutions question whose solution should be reviewed."),
    helpDuplicateBadge: message("helpDuplicateBadge", "Duplicate", "Status label for a Help & solutions question confirmed as a duplicate."),
    helpDuplicateDisputed: message("helpDuplicateDisputed", "Disputed", "Public neutral marker while a confirmed duplicate relationship has a pending author appeal."),
    helpDuplicateOf: message("helpDuplicateOf", "Duplicate of", "Text introducing the canonical original question for a confirmed duplicate."),
    helpDuplicateOriginalIdLabel: message("helpDuplicateOriginalIdLabel", "Original question ID", "Manager label for the canonical original Help question identifier."),
    helpDuplicateConfirm: message("helpDuplicateConfirm", "Confirm duplicate", "Manager action that confirms a Help question as a duplicate."),
    helpDuplicateRemove: message("helpDuplicateRemove", "Remove duplicate", "Manager action that removes a confirmed duplicate relationship."),
    helpDuplicateAppealHeading: message("helpDuplicateAppealHeading", "Dispute duplicate", "Heading for the duplicate-question author's appeal form."),
    helpDuplicateAppealExplanationLabel: message("helpDuplicateAppealExplanationLabel", "Why is this not a duplicate?", "Label for the required duplicate appeal explanation."),
    helpDuplicateAppealSubmit: message("helpDuplicateAppealSubmit", "Submit dispute", "Action for the duplicate-question author to submit an appeal."),
    helpDuplicateAppealPending: message("helpDuplicateAppealPending", "This duplicate status is disputed.", "Private author message while a duplicate appeal is pending."),
    helpDuplicateAppealReviewHeading: message("helpDuplicateAppealReviewHeading", "Duplicate dispute", "Manager heading above a pending duplicate appeal."),
    helpDuplicateAppealAccept: message("helpDuplicateAppealAccept", "Accept dispute and remove duplicate", "Manager action that accepts a duplicate appeal and removes the relationship."),
    helpDuplicateAppealReject: message("helpDuplicateAppealReject", "Reject dispute", "Manager action that rejects a duplicate appeal while preserving the relationship."),
    topicAdminPanel: message("topicAdminPanel", "Admin panel", "Manager-only administration controls for a forum topic."),
    helpSolutionOutdated: message("helpSolutionOutdated", "Solution outdated", "Status label for a solved Help & solutions question whose solution is outdated."),
    helpSolutionOutdatedReasonLabel: message("helpSolutionOutdatedReasonLabel", "Why this solution is outdated", "Label shown before the persisted reason explaining why a Help & solutions solution is outdated."),
    helpSolutionOutdatedReasonBestAnswerReplaced: message("helpSolutionOutdatedReasonBestAnswerReplaced", "A new best answer was selected.", "System-generated reason shown when a previous Help & solutions best answer becomes outdated because another answer was selected."),
    helpSolutionMarkNeedsReview: message("helpSolutionMarkNeedsReview", "Mark as needs review", "Moderator action that marks a solved Help & solutions solution as needing review."),
    helpSolutionOutdatedReasonInput: message("helpSolutionOutdatedReasonInput", "Reason the solution is outdated", "Label for the required reason when marking a Help & solutions solution outdated."),
    helpSolutionMarkOutdated: message("helpSolutionMarkOutdated", "Mark solution outdated", "Moderator action that marks a solved Help & solutions solution outdated."),
    helpSolutionClearModeration: message("helpSolutionClearModeration", "Clear solution status", "Moderator action that clears the Help & solutions solution moderation status."),
    helpSolutionsEmpty: message("helpSolutionsEmpty", "There are no questions yet.", "Empty state for the Help & solutions question list."),
    helpSolutionsOpen: message("helpSolutionsOpen", "Open", "Status label for a Help & solutions question that is not solved."),
    helpSolutionsReplyCount: pluralMessage(
      "helpSolutionsReplyCount",
      { one: "{{count}} reply", other: "{{count}} replies" },
      "Number of replies after the original Help & solutions question.",
      ["count"],
    ),
    helpSolutionsUpdated: message("helpSolutionsUpdated", "Updated {{time}}", "Latest activity label for a Help & solutions question.", ["time"]),
    helpSolutionsFiltersHeading: message("helpSolutionsFiltersHeading", "Filters", "Accessible label for the combined Help & solutions filters."),
    helpSolutionsFilterSolution: message("helpSolutionsFilterSolution", "Solution", "Label for the Help & solutions solution-state filter."),
    helpSolutionsFilterAnswers: message("helpSolutionsFilterAnswers", "Answers", "Label for the Help & solutions reply-presence filter."),
    helpSolutionsFilterQuality: message("helpSolutionsFilterQuality", "Quality", "Label for the Help & solutions question-quality filter."),
    helpSolutionsFilterRelation: message("helpSolutionsFilterRelation", "Relation", "Label for the Help & solutions duplicate-relation filter."),
    helpSolutionsFilterAny: message("helpSolutionsFilterAny", "Any", "Option that leaves one Help & solutions filter dimension unrestricted."),
    helpSolutionsFilterUnresolved: message("helpSolutionsFilterUnresolved", "Unresolved", "Filter option for Help questions that are not solved."),
    helpSolutionsFilterSolved: message("helpSolutionsFilterSolved", "Solved", "Filter option for solved Help questions."),
    helpSolutionsFilterNeedsReview: message("helpSolutionsFilterNeedsReview", "Needs review", "Moderator-only filter option for questions whose current solution needs review."),
    helpSolutionsFilterOutdated: message("helpSolutionsFilterOutdated", "Outdated", "Filter option for questions whose current solution is outdated."),
    helpSolutionsFilterNoAnswers: message("helpSolutionsFilterNoAnswers", "No answers", "Filter option for Help questions with no replies."),
    helpSolutionsFilterHasAnswers: message("helpSolutionsFilterHasAnswers", "Has answers", "Filter option for Help questions with at least one reply."),
    helpSolutionsFilterNormal: message("helpSolutionsFilterNormal", "Normal", "Filter option for Help questions without the Needs details label."),
    helpSolutionsFilterNeedsDetails: message("helpSolutionsFilterNeedsDetails", "Needs details", "Filter option for Help questions carrying the Needs details label."),
    helpSolutionsFilterStandalone: message("helpSolutionsFilterStandalone", "Standalone", "Filter option for Help questions that are not confirmed duplicates."),
    helpSolutionsFilterApply: message("helpSolutionsFilterApply", "Apply", "Action that applies the selected Help & solutions filters."),
    helpSolutionsFilterReset: message("helpSolutionsFilterReset", "Reset", "Action that clears all Help & solutions filters while preserving the current mode."),
    unansweredNav: message("unansweredNav", "Unanswered", "Homepage navigation entry for topics without an answer."),
    unansweredEyebrow: message("unansweredEyebrow", "Discovery", "Eyebrow above the Unanswered topics page heading."),
    unansweredHeading: message("unansweredHeading", "Unanswered topics", "Heading of the forum-wide Unanswered topics page."),
    unansweredIntro: message("unansweredIntro", "Topics that are not solved and have not received a reply yet.", "Short explanation of the Unanswered topics filter."),
    unansweredEmpty: message("unansweredEmpty", "There are no unanswered topics right now.", "Empty-state message for the Unanswered topics page."),
    unansweredNoReplies: message("unansweredNoReplies", "No replies yet", "Status label for a topic that has only its initial post."),
    tagsNav: message("tagsNav", "Tags", "Homepage navigation entry for technology tags."),
    tagsEyebrow: message("tagsEyebrow", "Discovery", "Eyebrow above the Tags discovery page heading."),
    tagsHeading: message("tagsHeading", "Technology tags", "Heading of the forum-wide technology Tags page."),
    tagsIntro: message("tagsIntro", "Browse forum topics by technology tag.", "Short explanation of the Tags discovery page."),
    tagsEmpty: message("tagsEmpty", "There are no tags yet.", "Empty-state message for the Tags discovery page."),
    tagTopicsHeading: message("tagTopicsHeading", "Topics tagged {{tag}}", "Accessible heading for topics filtered by one tag.", ["tag"]),
    tagTopicsIntro: message("tagTopicsIntro", "Topics using this tag.", "Short explanation above topics filtered by one tag."),
    tagTopicsEmpty: message("tagTopicsEmpty", "There are no topics with this tag.", "Empty-state message for a tag with no topics."),
    tagTopicCount: pluralMessage(
      "tagTopicCount",
      { one: "{{count}} topic", other: "{{count}} topics" },
      "Number of topics using a technology tag.",
      ["count"],
    ),
    topicTagsLabel: message("topicTagsLabel", "Tags", "Accessible label for topic technology tags."),
    topicTagsInputLabel: message("topicTagsInputLabel", "Tags", "Label for free-form tags on the create-topic form."),
    topicTagsInputHelp: message("topicTagsInputHelp", "Separate tags with commas, for example: TypeScript, Cloudflare, PostgreSQL.", "Help text for free-form topic tags.", [], ["TypeScript", "Cloudflare", "PostgreSQL"]),
    popularNav: message("popularNav", "Popular", "Homepage navigation entry for activity-ranked popular topics."),
    popularEyebrow: message("popularEyebrow", "Discovery", "Eyebrow above the Popular topics page heading."),
    popularHeading: message("popularHeading", "Popular topics", "Heading of the activity-ranked Popular topics page."),
    popularIntro: message("popularIntro", "Topics with the most message activity in each recent period.", "Short explanation of how Popular topics are ranked."),
    popularPeriod24h: message("popularPeriod24h", "24 hours", "Label for the Popular activity period covering the latest 24 hours."),
    popularPeriod7d: message("popularPeriod7d", "7 days", "Label for the Popular activity period covering the latest 7 days."),
    popularPeriod30d: message("popularPeriod30d", "30 days", "Label for the Popular activity period covering the latest 30 days."),
    popularEmpty: message("popularEmpty", "No topic activity in this period.", "Empty-state message for one Popular activity period."),
    unreadNav: message("unreadNav", "Unread", "Authenticated-only homepage navigation entry for unread topics."),
    unreadEyebrow: message("unreadEyebrow", "Discovery", "Eyebrow above the authenticated Unread topics page heading."),
    unreadHeading: message("unreadHeading", "Unread topics", "Heading of the authenticated Unread topics page."),
    unreadExistingHeading: message("unreadExistingHeading", "Unread", "Heading above topics with unread messages on the authenticated Unread page."),
    unreadNewHeading: message("unreadNewHeading", "New", "Heading above topics the current user has never opened on the authenticated Unread page."),
    unreadIntro: message("unreadIntro", "New topics and topics with messages you have not read yet.", "Short explanation of the authenticated Unread topics page."),
    unreadEmpty: message("unreadEmpty", "You have no unread topics.", "Empty-state message for the authenticated Unread topics page."),
    unreadNew: message("unreadNew", "New", "Status label for a topic the current user has never opened."),
    readStateRead: message("readStateRead", "Read", "Status label for a topic whose current messages have been read."),
    unreadCount: pluralMessage(
      "unreadCount",
      { one: "{{count}} unread message", other: "{{count}} unread messages" },
      "Number of unread messages after the current user's topic read marker.",
      ["count"],
    ),
    enterForumSection: message("enterForumSection", "Open {{section}}", "Accessible label for the vertical homepage category action.", ["section"]),
    forumDiscoveryDevelopmentStatus: message("forumDiscoveryDevelopmentStatus", "{{section}}: development status", "Accessible label while the homepage category action temporarily routes to the shared development page.", ["section"]),
    footerNavigation: message("footerNavigation", "Footer navigation", "Accessible label for the forum footer navigation."),
    rulesNav: message("rulesNav", "Rules", "Footer link to forum rules."),
    helpNav: message("helpNav", "Help", "Footer link to help."),
    aboutVicoNav: message("aboutVicoNav", "About Vico", "Footer link to product information.", [], ["Vico"]),
    feedbackNav: message("feedbackNav", "Feedback", "Footer link to feedback."),
    privacyNav: message("privacyNav", "Privacy", "Footer link to privacy information."),
    homeForumSectionsHeading: message("homeForumSectionsHeading", "Forum sections", "Heading above the primary forum blocks on the homepage."),
    pinnedHeading: message("pinnedHeading", "Pinned", "Heading for pinned topics in a homepage forum block."),
    latestTopicsHeading: message("latestTopicsHeading", "Latest topics", "Heading for latest topics in a homepage forum block."),
    homepageSectionFallbackDescription: message("homepageSectionFallbackDescription", "Sections, discussions, and practical answers in this area.", "Fallback description for a database-backed homepage category."),
    homepagePinnedEmpty: message("homepagePinnedEmpty", "No pinned topics yet.", "Empty state for a category-page section with no persisted pinned topics."),
    homepageLatestEmpty: message("homepageLatestEmpty", "No topics yet.", "Empty latest-topic area on a real homepage category."),
    homepageExpand: message("homepageExpand", "Show more topics", "Accessible label for expanding a homepage forum block."),
    homepageCollapse: message("homepageCollapse", "Show fewer topics", "Accessible label for collapsing a homepage forum block."),
    homepageMoreSections: pluralMessage(
      "homepageMoreSections",
      { one: "Show {{count}} more section", other: "Show {{count}} more sections" },
      "Homepage category action for revealing sections beyond the first three.",
      ["count"],
    ),
    homepageFewerSections: message(
      "homepageFewerSections",
      "Show fewer sections",
      "Homepage category action for hiding sections beyond the first three.",
    ),
    forumStatisticsHeading: message("forumStatisticsHeading", "Forum statistics", "Heading for aggregate homepage forum statistics."),
    whosOnlineHeading: message("whosOnlineHeading", "Who's online", "Heading for the homepage online-presence area."),
    onlinePresencePending: message("onlinePresencePending", "Online presence is still under development.", "Truthful placeholder while online presence is not implemented."),
    onlineActiveCount: message("onlineActiveCount", "Signed-in members active in the last 5 minutes: {{count}}", "Homepage online-presence count from server-authoritative recent heartbeats.", ["count"]),
    onlineNoMembers: message("onlineNoMembers", "No signed-in members active recently.", "Truthful empty state for the recent signed-in online-presence list."),
    onlinePresenceUnavailable: message("onlinePresenceUnavailable", "Online presence is temporarily unavailable.", "Homepage online-presence read failed; do not misrepresent unavailable data as zero members."),
    onlineMembersOnly: message("onlineMembersOnly", "Only signed-in members are counted; guests are not tracked.", "Scope note for the homepage online-presence data."),
    viewDevelopmentStatus: message("viewDevelopmentStatus", "View development status", "Link to the shared under-development status page."),
    underDevelopmentEyebrow: message("underDevelopmentEyebrow", "Pre-release", "Eyebrow for the shared under-development page."),
    underDevelopmentHeading: message("underDevelopmentHeading", "Under development", "Heading for the shared unfinished-function page."),
    underDevelopmentIntro: message("underDevelopmentIntro", "This page tracks approved Vico Forum functions that are not finished yet. Entry points stay visible during owner-only pre-release instead of pretending to work.", "Explanation of the shared pre-release under-development page.", [], ["Vico Forum"]),
    underDevelopmentRequested: message("underDevelopmentRequested", "{{feature}} is not finished yet.", "Status message for the unfinished feature that led to this page.", ["feature"]),
    underDevelopmentRemainingHeading: message("underDevelopmentRemainingHeading", "Still in development", "Heading above the current unfinished-feature checklist."),
    underDevelopmentBackToForum: message("underDevelopmentBackToForum", "Back to the forum", "Return link from the under-development page."),
    underDevelopmentFeatureSearch: message("underDevelopmentFeatureSearch", "Global forum search", "Unfinished feature label."),
    underDevelopmentFeatureNotifications: message("underDevelopmentFeatureNotifications", "Notifications", "Unfinished feature label."),
    underDevelopmentFeatureRegistration: message("underDevelopmentFeatureRegistration", "Account registration", "Unfinished feature label."),
    underDevelopmentFeaturePinnedTopics: message("underDevelopmentFeaturePinnedTopics", "Pinned-topic management", "Unfinished feature label."),
    underDevelopmentFeatureUnread: message("underDevelopmentFeatureUnread", "Unread/new state and jump to first unread", "Unfinished feature label."),
    underDevelopmentFeatureDrafts: message("underDevelopmentFeatureDrafts", "Drafts and autosave", "Unfinished feature label."),
    underDevelopmentFeatureProfiles: message("underDevelopmentFeatureProfiles", "Forum user profiles", "Unfinished feature label."),
    underDevelopmentFeatureTechnologyTags: message("underDevelopmentFeatureTechnologyTags", "Technology tags", "Unfinished feature label."),
    underDevelopmentFeatureUnansweredFilter: message("underDevelopmentFeatureUnansweredFilter", "Unanswered filter", "Unfinished feature label."),
    underDevelopmentFeaturePopular: message("underDevelopmentFeaturePopular", "Popular topics by activity period", "Unfinished feature label."),
    underDevelopmentFeatureForumDiscovery: message("underDevelopmentFeatureForumDiscovery", "Forum category and section presentation", "Unfinished forum discovery presentation label."),
    underDevelopmentFeatureMessageLinks: message("underDevelopmentFeatureMessageLinks", "Permanent message links and copy-link actions", "Unfinished feature label."),
    underDevelopmentFeatureReplyQuote: message("underDevelopmentFeatureReplyQuote", "Reply and quote relationships", "Unfinished feature label."),
    underDevelopmentFeatureEditor: message("underDevelopmentFeatureEditor", "Full editor and code tooling", "Unfinished feature label."),
    underDevelopmentFeatureOnlinePresence: message("underDevelopmentFeatureOnlinePresence", "Who's online", "Unfinished feature label."),
    underDevelopmentFeatureRules: message("underDevelopmentFeatureRules", "Forum rules page", "Unfinished content destination label."),
    underDevelopmentFeatureHelp: message("underDevelopmentFeatureHelp", "Help page", "Unfinished content destination label."),
    underDevelopmentFeatureAbout: message("underDevelopmentFeatureAbout", "About Vico", "Unfinished content destination label.", [], ["Vico"]),
    underDevelopmentFeatureFeedback: message("underDevelopmentFeatureFeedback", "Feedback", "Unfinished content destination label."),
    underDevelopmentFeaturePrivacy: message("underDevelopmentFeaturePrivacy", "Privacy page", "Unfinished content destination label."),
    signInGoogle: message("signInGoogle", "Sign in", "Google-backed sign-in button in the forum header."),
    signUp: message("signUp", "Sign up", "Future registration entry point in the forum header."),
    signOut: message("signOut", "Sign out", "Sign-out button in the forum header."),
    authPending: message("authPending", "Please wait…", "Pending label while an authentication request is running."),
    authError: message("authError", "Authentication failed. Please try again.", "Safe error shown when an authentication request fails."),
    forumIndex: message("forumIndex", "Forum index", "Link and eyebrow for the forum index."),
    categoriesHeading: message("categoriesHeading", "Categories", "Heading above the public category list."),
    categoriesIntro: message("categoriesIntro", "Browse the forum by category and section.", "Introduction to the forum index."),
    categoriesEmpty: message("categoriesEmpty", "There are no categories yet.", "Empty category list message."),
    sectionsEmpty: message("sectionsEmpty", "There are no sections in this category yet.", "Empty section list message."),
    topicsEmpty: message("topicsEmpty", "There are no topics in this section yet.", "Empty topic list message."),
    postsEmpty: message("postsEmpty", "There are no messages in this topic yet.", "Empty post list message."),
    breadcrumbsLabel: message("breadcrumbsLabel", "Breadcrumbs", "Accessible label for forum breadcrumbs."),
    categoryLabel: message("categoryLabel", "Category", "Category page type label."),
    sectionLabel: message("sectionLabel", "Section", "Section page type label."),
    topicLabel: message("topicLabel", "Topic", "Topic page type label."),
    topicsHeading: message("topicsHeading", "Topics", "Accessible heading for the topic table."),
    topicColumn: message("topicColumn", "Topic", "Topic table title column."),
    postsColumn: message("postsColumn", "Messages", "Topic table message-count column."),
    sectionCount: pluralMessage(
      "sectionCount",
      { one: "{{count}} section", other: "{{count}} sections" },
      "Number of sections in a category.",
      ["count"],
    ),
    topicCount: pluralMessage(
      "topicCount",
      { one: "{{count}} topic", other: "{{count}} topics" },
      "Number of topics in a section.",
      ["count"],
    ),
    messageCount: pluralMessage(
      "messageCount",
      { one: "{{count}} message", other: "{{count}} messages" },
      "Number of messages in a section.",
      ["count"],
    ),
    startedBy: message("startedBy", "Started by {{author}}", "Name of the topic author.", ["author"]),
    postNumber: message("postNumber", "Message #{{number}}", "Sequential message number.", ["number"]),
    copyMessageLink: message("copyMessageLink", "Copy link", "Action that copies a permanent link to a forum message."),
    copyMessageLinkFor: message("copyMessageLinkFor", "Copy link to {{message}}", "Accessible label for the action that copies a permanent forum message link.", ["message"]),
    messageLinkCopied: message("messageLinkCopied", "Copied", "Confirmation after a permanent forum message link is copied."),
    messageLinkCopyFailed: message("messageLinkCopyFailed", "Could not copy link.", "Failure feedback when a permanent forum message link cannot be copied."),
    messageActions: message("messageActions", "Actions", "Compact label for the mobile message actions menu."),
    replyToMessage: message("replyToMessage", "Reply", "Action that targets a reply at one forum message."),
    replyToMessageNumberCompact: message("replyToMessageNumberCompact", "Reply to #{{number}}", "Compact parent-message link used in the mobile message header.", ["number"]),
    directRepliesCompact: message("directRepliesCompact", "Replies", "Compact label for direct-reply links in a mobile message footer."),
    quoteSelectedText: message("quoteSelectedText", "Quote", "Action that inserts selected message text into the reply editor as a Markdown blockquote."),
    replyToMessageNumber: message("replyToMessageNumber", "Reply to Message #{{number}}", "Link from a direct reply to its parent message.", ["number"]),
    directReplies: message("directReplies", "Direct replies", "Label for links to messages that directly reply to this message."),
    replyingToMessage: message("replyingToMessage", "Replying to Message #{{number}}", "Reply editor banner showing the currently targeted parent message.", ["number"]),
    clearReplyTarget: message("clearReplyTarget", "Reply to topic instead", "Action that clears the targeted parent message from the reply editor."),
    quoteSelectionRequired: message("quoteSelectionRequired", "Select text in this message to quote it.", "Guidance shown when Quote is used without a valid text selection inside that message."),
    originalQuestion: message("originalQuestion", "Original question", "Label for the first message in a topic."),
    systemStateEyebrow: message("systemStateEyebrow", "System state", "Compact eyebrow for route error/system-state presentation."),
    routeBackToForum: message("routeBackToForum", "Back to forum", "Safe navigation action from a route error state."),
    routeUnauthenticatedHeading: message("routeUnauthenticatedHeading", "Sign in required", "Heading for a protected route shown without an authenticated session."),
    routeUnauthenticatedBody: message("routeUnauthenticatedBody", "Sign in to access this page.", "Explanation for a protected route shown without an authenticated session."),
    routeForbiddenHeading: message("routeForbiddenHeading", "Access denied", "Heading for an authenticated user without the required permission."),
    routeForbiddenBody: message("routeForbiddenBody", "You do not have permission to open this page.", "Explanation for an authenticated user without the required permission."),
    routeUnavailableHeading: message("routeUnavailableHeading", "Temporarily unavailable", "Heading for a controlled temporary dependency outage."),
    routeUnavailableBody: message("routeUnavailableBody", "This part of Vico Forum is temporarily unavailable. Please try again later.", "Explanation for a controlled temporary dependency outage."),
    forumNotFoundHeading: message("forumNotFoundHeading", "Forum page not found", "Forum not-found heading."),
    forumNotFoundBody: message("forumNotFoundBody", "The category, section, or topic does not exist.", "Forum not-found explanation."),
    forumErrorHeading: message("forumErrorHeading", "The forum could not be loaded", "Forum read error heading."),
    forumErrorBody: message("forumErrorBody", "Please try again later.", "Forum read error explanation."),
    authoringLabel: message("authoringLabel", "Write", "Compact eyebrow above forum authoring forms."),
    createTopicHeading: message("createTopicHeading", "Create a new topic", "Heading above the authenticated topic form."),
    createTopicHelp: message("createTopicHelp", "Start a focused discussion in this section.", "Short guidance beside the create-topic heading."),
    topicTitleLabel: message("topicTitleLabel", "Topic title", "Label for a new topic title."),
    topicTitleHelp: message("topicTitleHelp", "Use a clear, specific title.", "Help text below the topic-title field."),
    initialPostLabel: message("initialPostLabel", "First message", "Label for a new topic's first message."),
    createTopicSubmit: message("createTopicSubmit", "Create topic", "Submit button for a new topic."),
    createTopicSubmitting: message("createTopicSubmitting", "Creating topic…", "Pending label while a new topic is being submitted."),
    replyHeading: message("replyHeading", "Add a reply", "Heading above the authenticated reply form."),
    replyHelp: message("replyHelp", "Add useful context, an answer, or a follow-up.", "Short guidance beside the reply heading."),
    replyBodyLabel: message("replyBodyLabel", "Reply", "Label for a reply body."),
    replySubmit: message("replySubmit", "Post reply", "Submit button for a reply."),
    replySubmitting: message("replySubmitting", "Posting reply…", "Pending label while a reply is being submitted."),
    messageBodyHelp: message("messageBodyHelp", "Markdown and fenced code blocks are supported.", "Help text below forum message textareas."),
    editorToolbar: message("editorToolbar", "Markdown formatting", "Accessible label for the Markdown editor formatting toolbar."),
    editorViewMode: message("editorViewMode", "Editor view", "Accessible label for choosing the Markdown editor view mode."),
    editorModeWrite: message("editorModeWrite", "Write", "Markdown editor mode that shows the editable source."),
    editorModePreview: message("editorModePreview", "Preview", "Markdown editor mode that shows the rendered preview."),
    editorModeSplit: message("editorModeSplit", "Split", "Markdown editor mode that shows source and preview side by side."),
    editorHeading: message("editorHeading", "Heading", "Markdown editor action that turns the current line or selection into a level-two heading."),
    editorBold: message("editorBold", "Bold", "Markdown editor action that wraps the current selection in bold markers."),
    editorItalic: message("editorItalic", "Italic", "Markdown editor action that wraps the current selection in italic markers."),
    editorInlineCode: message("editorInlineCode", "Inline code", "Markdown editor action that wraps the current selection in inline-code markers."),
    editorCodeBlock: message("editorCodeBlock", "Code block", "Markdown editor action that inserts a fenced code block."),
    editorQuote: message("editorQuote", "Quote", "Markdown editor action that prefixes the current line or selection as a blockquote."),
    editorLink: message("editorLink", "Link", "Markdown editor action that inserts a Markdown link around the current selection."),
    editorBulletedList: message("editorBulletedList", "Bulleted list", "Markdown editor action that prefixes selected lines as a bulleted list."),
    editorNumberedList: message("editorNumberedList", "Numbered list", "Markdown editor action that prefixes selected lines as a numbered list."),
    editorCodeLanguage: message("editorCodeLanguage", "Code language", "Label for the optional fenced-code language identifier."),
    editorCodeLanguagePlaceholder: message("editorCodeLanguagePlaceholder", "e.g. ts", "Example value for the optional fenced-code language identifier."),
    editorPreviewHeading: message("editorPreviewHeading", "Markdown preview", "Heading for the authoring Markdown preview panel."),
    editorPreviewEmpty: message("editorPreviewEmpty", "Nothing to preview yet.", "Empty state shown when the Markdown preview has no body content."),
    codeLanguagePlainText: message("codeLanguagePlainText", "Plain text", "Language label used for a fenced code block without a language identifier."),
    codeCopy: message("codeCopy", "Copy code", "Action that copies one rendered code block."),
    codeCopied: message("codeCopied", "Code copied", "Confirmation shown after rendered code is copied."),
    codeCopyFailed: message("codeCopyFailed", "Could not copy code.", "Failure feedback when rendered code cannot be copied."),
    codeWrap: message("codeWrap", "Wrap lines", "Action that enables wrapping for a rendered code block."),
    codeNoWrap: message("codeNoWrap", "No wrap", "Action that disables wrapping for a rendered code block."),
    authoringRequiredHint: message("authoringRequiredHint", "All fields are required.", "Required-field hint in forum authoring forms."),
    solved: message("solved", "Solved", "Solved topic status."),
    markSolved: message("markSolved", "Mark as solved", "Action for the topic author to mark a topic solved."),
    bestAnswer: message("bestAnswer", "Best answer", "Label on the selected best answer."),
    selectBestAnswer: message("selectBestAnswer", "Select as best answer", "Action for the topic author to select a post."),
    problemSolvedPrompt: message("problemSolvedPrompt", "Problem solved?", "Confirmation shown to a topic author after selecting a best answer on an unsolved topic."),
    problemSolvedYes: message("problemSolvedYes", "Yes, mark as solved", "Confirmation action that marks the topic solved after selecting a best answer."),
    problemSolvedNo: message("problemSolvedNo", "No, keep it unsolved", "Dismissal action that keeps the topic unsolved after selecting a best answer."),
    goToSolution: message("goToSolution", "Go to solution", "Link from the topic heading to the best answer."),
    topicTools: message("topicTools", "Topic tools", "Progressive-disclosure label for secondary topic management controls."),
    pinTopic: message("pinTopic", "Pin topic", "Action for authorized users to pin the current topic."),
    unpinTopic: message("unpinTopic", "Unpin topic", "Action for authorized users to remove the current topic pin."),
    messageTools: message("messageTools", "Message tools", "Progressive-disclosure label for secondary message management controls."),
    automaticTranslation: message("automaticTranslation", "Automatic translation", "Marker for a machine-translated forum content unit."),
    manualTranslation: message("manualTranslation", "Manual translation", "Marker for a persisted manual forum content translation."),
    showOriginal: message("showOriginal", "Show original", "Control that reveals the original forum content beside a translation."),
    hideOriginal: message("hideOriginal", "Hide original", "Control that collapses the revealed original forum content beneath a translation."),
    showTranslation: message("showTranslation", "Show translation", "Control that returns focus to the translated forum content."),
    translationRequesting: message("translationRequesting", "Requesting translation…", "Accessible pending feedback while a content translation request is being submitted."),
    translationPending: message("translationPending", "Translation queued.", "Content translation task is queued and waiting to run."),
    translationProcessing: message("translationProcessing", "Translation is being prepared.", "Content translation task is currently processing."),
    translationConverging: message("translationConverging", "Translation is becoming available.", "Read-only convergence feedback when task completion is newer than the independently read presentation."),
    translationDeferred: message("translationDeferred", "Translation is temporarily deferred.", "Content translation task is durably deferred."),
    translationDeferredFor: message("translationDeferredFor", "Translation is deferred. Try again in about {{seconds}} seconds.", "Deferred content translation feedback with bounded retry timing.", ["seconds"]),
    translationFailed: message("translationFailed", "Translation could not be completed.", "Terminal content translation failure feedback."),
    translationUnavailable: message("translationUnavailable", "Translation is temporarily unavailable.", "Temporary generation or status-storage availability feedback."),
    translationExplicitRequired: message("translationExplicitRequired", "This long message requires an explicit translation request.", "Long post body requires an explicit user action before translation planning."),
    translationExplicitAction: message("translationExplicitAction", "Translate this message", "Explicit translation action for a long post body."),
    translationCurrent: message("translationCurrent", "Translation is current.", "Exact-current translated content is already displayed."),
    translationRequestChanged: message("translationRequestChanged", "The content or translation state changed. Review the current page.", "Safe feedback when a generation request becomes ineligible or stale."),
    translationRetryAfter: message("translationRetryAfter", "Translation requests are limited. Try again in {{seconds}} seconds.", "Bounded request-budget feedback without exposing quota internals.", ["seconds"]),
    sourceLocaleCurrent: message("sourceLocaleCurrent", "Source language: {{locale}}", "Current source-language metadata for forum content.", ["locale"]),
    sourceLocaleCorrectionInput: message("sourceLocaleCorrectionInput", "Correct source language", "Label for the source-language correction input."),
    sourceLocaleCorrectionSubmit: message("sourceLocaleCorrectionSubmit", "Correct language", "Submit action for source-language metadata correction."),
    sourceLocaleCorrectionError_invalid: message("sourceLocaleCorrectionError_invalid", "Enter a valid BCP-47 source language.", "Invalid source-language correction."),
    sourceLocaleCorrectionError_unauthenticated: message("sourceLocaleCorrectionError_unauthenticated", "Sign in to correct the source language.", "Unauthenticated source-language correction."),
    sourceLocaleCorrectionError_origin: message("sourceLocaleCorrectionError_origin", "This correction request could not be verified.", "Origin failure for source-language correction."),
    sourceLocaleCorrectionError_forbidden: message("sourceLocaleCorrectionError_forbidden", "You cannot correct the source language for this content.", "Forbidden source-language correction."),
    sourceLocaleCorrectionError_notFound: message("sourceLocaleCorrectionError_notFound", "The content to correct no longer exists.", "Missing source-language correction target."),
    sourceLocaleCorrectionError_conflict: message("sourceLocaleCorrectionError_conflict", "The content changed before the source language could be corrected. Reload and try again.", "Stale source-language correction."),
    sourceLocaleCorrectionError_unavailable: message("sourceLocaleCorrectionError_unavailable", "The source language could not be corrected. Please try again later.", "Temporary source-language correction storage failure."),
    forumWriteError_invalid: message("forumWriteError_invalid", "Enter all required fields.", "Forum mutation validation error."),
    forumWriteError_unauthenticated: message("forumWriteError_unauthenticated", "Sign in to continue.", "Forum mutation authentication error."),
    forumWriteError_origin: message("forumWriteError_origin", "This request could not be verified.", "Forum mutation origin error."),
    forumWriteError_forbidden: message("forumWriteError_forbidden", "Only the topic author can change its solution.", "Forum solution authorization error."),
    forumWriteError_conflict: message("forumWriteError_conflict", "That solution cannot be selected for this topic.", "Forum solution state conflict."),
    forumWriteError_notFound: message("forumWriteError_notFound", "The target section or topic no longer exists.", "Forum mutation missing target error."),
    forumWriteError_rateLimited: message("forumWriteError_rateLimited", "Please wait a few seconds before posting again.", "Forum mutation rate limit error."),
    forumWriteError_unavailable: message("forumWriteError_unavailable", "Your message could not be saved. Please try again.", "Forum mutation storage error."),
    authorizationNav: message("authorizationNav", "Authorization", "Link to authorization management."),
    authorizationHeading: message("authorizationHeading", "Authorization management", "Authorization management page heading."),
    rolesHeading: message("rolesHeading", "Roles", "Role management heading."),
    usersHeading: message("usersHeading", "Users", "User authorization heading."),
    roleSlug: message("roleSlug", "Role slug", "Role slug field label."),
    displayName: message("displayName", "Display name", "Role display-name field label."),
    createRole: message("createRole", "Create custom role", "Create-role action."),
    save: message("save", "Save", "Generic save action."),
    deleteRole: message("deleteRole", "Delete role", "Delete-role action."),
    builtInRole: message("builtInRole", "Built-in", "Built-in role marker."),
    permissionsHeading: message("permissionsHeading", "Permissions", "Permissions heading."),
    effectivePermissions: message("effectivePermissions", "Effective permissions", "Effective permissions heading."),
    assignedRole: message("assignedRole", "Assigned role", "Assigned role field label."),
    defaultRole: message("defaultRole", "Default role", "Default role marker."),
    overrideInherit: message("overrideInherit", "Inherit", "Inherited permission option."),
    overrideAllow: message("overrideAllow", "Allow", "Allowed permission option."),
    overrideDeny: message("overrideDeny", "Deny", "Denied permission option."),
    authorizationSaved: message("authorizationSaved", "Authorization was updated.", "Successful authorization mutation message."),
    authorizationError_invalid: message("authorizationError_invalid", "Check the submitted values.", "Invalid authorization mutation."),
    authorizationError_forbidden: message("authorizationError_forbidden", "You cannot manage authorization.", "Forbidden authorization mutation."),
    authorizationError_notFound: message("authorizationError_notFound", "The selected role or user no longer exists.", "Missing authorization entity."),
    authorizationError_conflict: message("authorizationError_conflict", "This change would cause a lockout or the role is assigned.", "Authorization conflict."),
    authorizationError_unavailable: message("authorizationError_unavailable", "Authorization is temporarily unavailable.", "Authorization infrastructure error."),
  },
} as const satisfies Record<string, Record<string, UiMessageDescriptor>>;

function message<const Key extends string, const Source extends string>(
  key: Key,
  source: Source,
  description: string,
  placeholders: readonly string[] = [],
  protectedTerms: readonly string[] = [],
) {
  return {
    namespace: "common",
    key,
    source,
    description,
    placeholders,
    messageKind: placeholders.length === 0 ? "plain" : "interpolation",
    protectedTerms,
  } as const satisfies UiMessageDescriptor;
}

function pluralMessage<const Key extends string, const Source extends UiStructuredMessageSource>(
  key: Key,
  source: Source,
  description: string,
  placeholders: readonly string[],
  protectedTerms: readonly string[] = [],
) {
  return {
    namespace: "common",
    key,
    source,
    description,
    placeholders,
    messageKind: "plural",
    protectedTerms,
  } as const satisfies UiMessageDescriptor;
}

export type UiNamespace = keyof typeof canonicalEnglishCatalog;
export type UiKey<N extends UiNamespace> = keyof (typeof canonicalEnglishCatalog)[N] & string;
type DescriptorSource<T> = T extends { readonly source: infer Source }
  ? Source extends string ? Source : string
  : never;
export type CanonicalResourceShape = {
  [N in UiNamespace]: {
    [K in UiKey<N>]: DescriptorSource<(typeof canonicalEnglishCatalog)[N][K]>;
  };
};

export function catalogDescriptors(): UiMessageDescriptor[] {
  return Object.values(canonicalEnglishCatalog).flatMap((namespace) =>
    Object.values(namespace) as UiMessageDescriptor[],
  );
}
