import type { UiKey } from "./catalog";
import type { ProviderTranslationValue } from "./translation-validation";

type CommonTranslationValues = Readonly<Record<UiKey<"common">, ProviderTranslationValue>>;

export const russianCommonValues = {
  profileHeading: "Форумный профиль",
  profileEdit: "Редактировать профиль",
  profileJoined: "На форуме с",
  profileMessages: "Сообщения",
  profileBestAnswers: "Лучшие ответы",
  profileBio: "О себе",
  profileNoBio: "Описание пока не добавлено.",
  profileLinks: "Ссылки пользователя",
  profileWebsite: "Сайт",
  profileBioHint: "До 500 символов. Описание видно всем.",
  profileGithubHint: "Ссылка на публичный профиль GitHub. Необязательно.",
  profileWebsiteHint: "Полная ссылка с HTTP или HTTPS. Необязательно.",
  profileSave: "Сохранить профиль",
  profileSaving: "Сохраняю…",
  profileCancel: "Отмена",
  profileSaved: "Профиль сохранён.",
  profileInvalid: "Описание — до 500 символов. Проверьте ссылки: GitHub должен вести на профиль пользователя.",
  profileRoleUser: "Участник",
  profileRoleModerator: "Модератор",
  profileRoleAdmin: "Администратор",
  profileError_unauthenticated: "Войдите, чтобы редактировать свой профиль.",
  profileError_origin: "Не удалось проверить запрос.",
  profileError_forbidden: "Можно редактировать только свой профиль.",
  profileError_notFound: "Этот профиль больше не существует.",
  profileError_unavailable: "Не удалось сохранить профиль. Попробуйте ещё раз.",

  productName: "Vico Forum",
  heading: "Основа переводов",
  stageSummary: "Stage 1 закладывает маршрутизацию с учётом локали и синхронизированный перевод интерфейса.",
  forumTagline: "Вопросы, обсуждения и практические ответы",
  primaryNavigation: "Основная навигация",
  skipToContent: "Перейти к содержимому",
  themeLabel: "Тема",
  lightTheme: "Светлая",
  darkTheme: "Тёмная",
  switchToLightTheme: "Переключить на светлую тему",
  switchToDarkTheme: "Переключить на тёмную тему",
  searchForum: "Поиск по форуму",
  searchEyebrow: "Обзор",
  searchHeading: "Поиск",
  searchIntro: "Ищите по текущим заголовкам тем, сообщениям и технологическим тегам.",
  searchInputLabel: "Поисковый запрос",
  searchInputPlaceholder: "Введите слова из темы, сообщения или тега",
  searchSubmit: "Найти",
  searchPrompt: "Введите запрос, чтобы найти темы форума.",
  searchTooLong: "Поисковый запрос может содержать не более 200 символов.",
  searchNoResults: "По запросу «{{query}}» темы не найдены.",
  searchResultsHeading: "Результаты для «{{query}}»",
  searchResultCount: {
    one: "{{count}} результат",
    few: "{{count}} результата",
    many: "{{count}} результатов",
    other: "{{count}} результата",
  },
  notifications: "Уведомления",
  notificationsUnreadLabel: "Уведомления, непрочитанных: {{count}}",
  notificationIntro: "Ответы на ваши темы и сообщения.",
  notificationEmpty: "Уведомлений нет.",
  notificationReplyBy: "Ответ от {{actor}}",
  notificationUnread: "Непрочитано",
  notificationRead: "Прочитано",
  notificationOpen: "Открыть ответ",
  forumHomeNav: "Главная",
  helpSolutionsHeading: "Помощь и решения",
  helpSolutionsIntro: "Технические вопросы, поиск причин проблем и практические решения от сообщества.",
  helpSolutionsAllMode: "Все",
  helpSolutionsAllHeading: "Все вопросы",
  helpSolutionsNeedsHelpMode: "Нужна помощь",
  helpSolutionsNeedsHelpHeading: "Вопросы, которым нужна помощь",
  helpSolutionsNeedsHelpEmpty: "Сейчас нет вопросов, которым нужна помощь.",
  helpSolutionsWantToHelpMode: "Хочу помочь",
  helpSolutionsWantToHelpHeading: "Вопросы, с которыми можно помочь",
  helpSolutionsWantToHelpEmpty: "Сейчас нет открытых вопросов других пользователей.",
  helpSolutionsForMeMode: "Для меня",
  helpSolutionsForMeHeading: "Вопросы для меня",
  helpSolutionsForMeEmpty: "Сейчас нет подходящих открытых вопросов для вас.",
  helpSolutionsActiveMode: "Активные",
  helpSolutionsActiveHeading: "Активные вопросы",
  helpSolutionsActiveEmpty: "Сейчас нет активных вопросов.",
  helpSolutionsNeedsAttentionMode: "Требуют внимания",
  helpSolutionsNeedsAttentionHeading: "Вопросы, требующие внимания",
  helpSolutionsNeedsAttentionEmpty: "Сейчас нет вопросов, требующих внимания.",
  helpSolutionsMineMode: "Мои",
  helpSolutionsMineHeading: "Мои вопросы",
  helpSolutionsMineEmpty: "Вы ещё не задавали вопросов.",
  helpSolutionsSimilarCheck: "Проверить похожие вопросы",
  helpSolutionsSimilarChecking: "Проверяем…",
  helpSolutionsSimilarHeading: "Похожие вопросы",
  helpSolutionsSimilarIntro: "Посмотрите эти существующие вопросы перед публикацией. Новый вопрос всё равно можно опубликовать.",
  helpSolutionsSimilarEmpty: "Похожих вопросов не найдено.",
  helpSolutionsSimilarInvalid: "Введите заголовок вопроса длиной до 200 символов, чтобы проверить похожие вопросы.",
  helpSolutionsSimilarUnavailable: "Проверка похожих вопросов временно недоступна. Вы всё равно можете опубликовать вопрос.",
  helpSolutionsSimilarMatchTitle: "Найдено в заголовке",
  helpSolutionsSimilarMatchTags: "Найдено в тегах",
  helpSolutionsSimilarMatchBody: "Найдено в обсуждении",
  helpSolutionsAskHeading: "Задать вопрос",
  helpSolutionsAskHelp: "Опишите проблему достаточно подробно, чтобы другие могли её воспроизвести и решить.",
  helpSolutionsQuestionTitleLabel: "Заголовок вопроса",
  helpSolutionsQuestionBodyLabel: "Описание вопроса",
  helpSolutionsAskSubmit: "Задать вопрос",
  helpSolutionsAskSubmitting: "Публикуем вопрос…",
  helpSolutionsSolutionsMode: "Решения",
  helpSolutionsSolutionsHeading: "Решённые вопросы",
  helpSolutionsSolutionsEmpty: "Решённых вопросов пока нет.",
  helpSolutionNeedsReview: "Требует проверки",
  helpDuplicateBadge: "Дубликат",
  helpDuplicateDisputed: "Оспаривается",
  helpDuplicateOf: "Дубликат:",
  helpDuplicateOriginalIdLabel: "ID исходного вопроса",
  helpDuplicateConfirm: "Подтвердить дубликат",
  helpDuplicateRemove: "Снять статус дубликата",
  helpDuplicateAppealHeading: "Оспорить дубликат",
  helpDuplicateAppealExplanationLabel: "Почему этот вопрос не является дубликатом?",
  helpDuplicateAppealSubmit: "Отправить оспаривание",
  helpDuplicateAppealPending: "Статус дубликата оспаривается.",
  helpDuplicateAppealReviewHeading: "Оспаривание дубликата",
  helpDuplicateAppealAccept: "Принять оспаривание и снять дубликат",
  helpDuplicateAppealReject: "Отклонить оспаривание",
  topicAdminPanel: "Админ панель",
  helpSolutionOutdated: "Решение устарело",
  helpSolutionOutdatedReasonLabel: "Почему решение устарело",
  helpSolutionOutdatedReasonBestAnswerReplaced: "Выбран новый лучший ответ.",
  helpSolutionMarkNeedsReview: "Отметить как требующее проверки",
  helpSolutionOutdatedReasonInput: "Причина, почему решение устарело",
  helpSolutionMarkOutdated: "Отметить решение как устаревшее",
  helpSolutionClearModeration: "Снять пометку решения",
  helpSolutionsEmpty: "Вопросов пока нет.",
  helpSolutionsOpen: "Открыт",
  helpSolutionsReplyCount: {
    one: "{{count}} ответ",
    few: "{{count}} ответа",
    many: "{{count}} ответов",
    other: "{{count}} ответа",
  },
  helpSolutionsUpdated: "Обновлено {{time}}",
  helpSolutionsFiltersHeading: "Фильтры",
  helpSolutionsFilterSolution: "Решение",
  helpSolutionsFilterAnswers: "Ответы",
  helpSolutionsFilterQuality: "Качество",
  helpSolutionsFilterRelation: "Связь",
  helpSolutionsFilterAny: "Любое",
  helpSolutionsFilterUnresolved: "Нерешён",
  helpSolutionsFilterSolved: "Решён",
  helpSolutionsFilterNeedsReview: "Требует проверки",
  helpSolutionsFilterOutdated: "Устарело",
  helpSolutionsFilterNoAnswers: "Без ответов",
  helpSolutionsFilterHasAnswers: "Есть ответы",
  helpSolutionsFilterNormal: "Нормальный",
  helpSolutionsFilterNeedsDetails: "Нужны детали",
  helpSolutionsFilterStandalone: "Самостоятельный",
  helpSolutionsFilterApply: "Применить",
  helpSolutionsFilterReset: "Сбросить",
  unansweredNav: "Без ответа",
  unansweredEyebrow: "Обзор",
  unansweredHeading: "Темы без ответа",
  unansweredIntro: "Темы, которые ещё не решены и пока не получили ни одного ответа.",
  unansweredEmpty: "Сейчас нет тем без ответа.",
  unansweredNoReplies: "Ответов пока нет",
  tagsNav: "Теги",
  tagsEyebrow: "Обзор",
  tagsHeading: "Технологические теги",
  tagsIntro: "Просматривайте темы форума по технологическим тегам.",
  tagsEmpty: "Тегов пока нет.",
  tagTopicsHeading: "Темы с тегом {{tag}}",
  tagTopicsIntro: "Темы форума с этим тегом.",
  tagTopicsEmpty: "Тем с этим тегом пока нет.",
  tagTopicCount: {
    one: "{{count}} тема",
    few: "{{count}} темы",
    many: "{{count}} тем",
    other: "{{count}} темы",
  },
  topicTagsLabel: "Теги",
  topicTagsInputLabel: "Теги",
  topicTagsInputHelp: "Разделяйте теги запятыми, например: TypeScript, Cloudflare, PostgreSQL.",
  popularNav: "Популярное",
  popularEyebrow: "Обзор",
  popularHeading: "Популярные темы",
  popularIntro: "Темы с наибольшей активностью сообщений за каждый недавний период.",
  popularPeriod24h: "24 часа",
  popularPeriod7d: "7 дней",
  popularPeriod30d: "30 дней",
  popularEmpty: "За этот период активности в темах нет.",
  unreadNav: "Непрочитанное",
  unreadEyebrow: "Обзор",
  unreadHeading: "Непрочитанные темы",
  unreadExistingHeading: "Непрочитанные",
  unreadNewHeading: "Новые",
  unreadIntro: "Новые темы и темы с сообщениями, которые вы ещё не читали.",
  unreadEmpty: "Непрочитанных тем нет.",
  unreadNew: "Новая",
  readStateRead: "Прочитано",
  unreadCount: {
    one: "{{count}} непрочитанное сообщение",
    few: "{{count}} непрочитанных сообщения",
    many: "{{count}} непрочитанных сообщений",
    other: "{{count}} непрочитанного сообщения",
  },
  enterForumSection: "Открыть {{section}}",
  forumDiscoveryDevelopmentStatus: "{{section}}: статус разработки",
  footerNavigation: "Навигация в подвале",
  rulesNav: "Правила",
  helpNav: "Помощь",
  aboutVicoNav: "О Vico",
  feedbackNav: "Обратная связь",
  privacyNav: "Конфиденциальность",
  homeForumSectionsHeading: "Разделы форума",
  pinnedHeading: "Закреплённые",
  latestTopicsHeading: "Последние темы",
  homepageSectionFallbackDescription: "Разделы, обсуждения и практические ответы по этой теме.",
  homepagePinnedEmpty: "Закреплённых тем пока нет.",
  homepageLatestEmpty: "Тем пока нет.",
  homepageExpand: "Показать больше тем",
  homepageCollapse: "Показать меньше тем",
  homepageMoreSections: {
    one: "Показать ещё {{count}} раздел",
    few: "Показать ещё {{count}} раздела",
    many: "Показать ещё {{count}} разделов",
    other: "Показать ещё {{count}} раздела",
  },
  homepageFewerSections: "Показать меньше разделов",
  forumStatisticsHeading: "Статистика форума",
  whosOnlineHeading: "Кто онлайн",
  onlinePresencePending: "Отображение пользователей онлайн ещё в разработке.",
  onlineActiveCount: "Активных участников за последние 5 минут: {{count}}",
  onlineNoMembers: "Сейчас нет активных участников.",
  onlinePresenceUnavailable: "Сведения об участниках онлайн временно недоступны.",
  onlineMembersOnly: "Учитываются только вошедшие пользователи; гости не отслеживаются.",
  viewDevelopmentStatus: "Посмотреть статус разработки",
  underDevelopmentEyebrow: "Предрелиз",
  underDevelopmentHeading: "В разработке",
  underDevelopmentIntro: "На этой странице перечислены утверждённые функции Vico Forum, которые ещё не готовы. Во время предрелизной проверки точки входа остаются видимыми, а не имитируют несуществующую работу.",
  underDevelopmentRequested: "{{feature}} пока не готово.",
  underDevelopmentRemainingHeading: "Ещё в разработке",
  underDevelopmentBackToForum: "Вернуться на форум",
  underDevelopmentFeatureSearch: "Глобальный поиск по форуму",
  underDevelopmentFeatureNotifications: "Уведомления",
  underDevelopmentFeatureRegistration: "Регистрация аккаунта",
  underDevelopmentFeaturePinnedTopics: "Управление закреплёнными темами",
  underDevelopmentFeatureUnread: "Непрочитанное/новое и переход к первому непрочитанному",
  underDevelopmentFeatureDrafts: "Черновики и автосохранение",
  underDevelopmentFeatureProfiles: "Профили пользователей форума",
  underDevelopmentFeatureTechnologyTags: "Технологические теги",
  underDevelopmentFeatureUnansweredFilter: "Фильтр тем без ответа",
  underDevelopmentFeaturePopular: "Популярные темы по периоду активности",
  underDevelopmentFeatureForumDiscovery: "Представление категорий и разделов форума",
  underDevelopmentFeatureMessageLinks: "Постоянные ссылки на сообщения и копирование ссылок",
  underDevelopmentFeatureReplyQuote: "Связи ответов и цитат",
  underDevelopmentFeatureEditor: "Полноценный редактор и инструменты для кода",
  underDevelopmentFeatureOnlinePresence: "Кто онлайн",
  underDevelopmentFeatureRules: "Страница правил форума",
  underDevelopmentFeatureHelp: "Страница помощи",
  underDevelopmentFeatureAbout: "О Vico",
  underDevelopmentFeatureFeedback: "Обратная связь",
  underDevelopmentFeaturePrivacy: "Страница конфиденциальности",
  authEmailHeading: "Вход на Vico Forum",
  authRegisterHeading: "Создать аккаунт",
  authEmailName: "Имя на форуме",
  authEmailAddress: "Email",
  authEmailPassword: "Пароль",
  authEmailPasswordHint: "От 8 до 128 символов.",
  authEmailSubmit: "Войти по email",
  authRegisterSubmit: "Создать аккаунт",
  authGoogleOption: "Продолжить с Google",
  authSwitchToRegister: "Нет аккаунта? Зарегистрироваться",
  authSwitchToSignIn: "Уже есть аккаунт? Войти",
  authEmailFailure: "Не удалось войти. Проверьте email и пароль.",
  authRegisterFailure: "Не удалось зарегистрироваться. Проверьте данные или используйте другой email.",
  authEmailNoVerification: "Подтверждение почты и восстановление пароля пока недоступны.",
  signInGoogle: "Войти",
  signUp: "Регистрация",
  signOut: "Выйти",
  authPending: "Подождите…",
  authError: "Не удалось выполнить вход. Попробуйте ещё раз.",
  forumIndex: "Главная форума",
  categoriesHeading: "Категории",
  categoriesIntro: "Просматривайте форум по категориям и разделам.",
  categoriesEmpty: "Категорий пока нет.",
  sectionsEmpty: "В этой категории пока нет разделов.",
  topicsEmpty: "В этом разделе пока нет тем.",
  postsEmpty: "В этой теме пока нет сообщений.",
  breadcrumbsLabel: "Навигационная цепочка",
  categoryLabel: "Категория",
  sectionLabel: "Раздел",
  topicLabel: "Тема",
  topicsHeading: "Темы",
  topicColumn: "Тема",
  postsColumn: "Сообщения",
  sectionCount: {
    one: "{{count}} раздел",
    few: "{{count}} раздела",
    many: "{{count}} разделов",
    other: "{{count}} раздела",
  },
  topicCount: {
    one: "{{count}} тема",
    few: "{{count}} темы",
    many: "{{count}} тем",
    other: "{{count}} темы",
  },
  messageCount: {
    one: "{{count}} сообщение",
    few: "{{count}} сообщения",
    many: "{{count}} сообщений",
    other: "{{count}} сообщения",
  },
  startedBy: "Автор: {{author}}",
  postNumber: "Сообщение №{{number}}",
  copyMessageLink: "Копировать ссылку",
  copyMessageLinkFor: "Копировать ссылку на {{message}}",
  messageLinkCopied: "Скопировано",
  messageLinkCopyFailed: "Не удалось скопировать ссылку.",
  messageActions: "Действия",
  replyToMessage: "Ответить",
  quoteSelectedText: "Цитировать",
  replyToMessageNumber: "Ответ на сообщение №{{number}}",
  replyToMessageNumberCompact: "Ответ на #{{number}}",
  directReplies: "Прямые ответы",
  directRepliesCompact: "Ответы",
  replyingToMessage: "Ответ на сообщение №{{number}}",
  clearReplyTarget: "Ответить в тему",
  quoteSelectionRequired: "Выделите текст в этом сообщении, чтобы процитировать его.",
  originalQuestion: "Исходный вопрос",
  systemStateEyebrow: "Системное состояние",
  routeBackToForum: "Вернуться на форум",
  routeUnauthenticatedHeading: "Требуется вход",
  routeUnauthenticatedBody: "Войдите в аккаунт, чтобы открыть эту страницу.",
  routeForbiddenHeading: "Доступ запрещён",
  routeForbiddenBody: "У вас нет разрешения на просмотр этой страницы.",
  routeUnavailableHeading: "Временно недоступно",
  routeUnavailableBody: "Эта часть Vico Forum временно недоступна. Попробуйте ещё раз позже.",
  forumNotFoundHeading: "Страница форума не найдена",
  forumNotFoundBody: "Категория, раздел или тема не существует.",
  forumErrorHeading: "Не удалось загрузить форум",
  forumErrorBody: "Попробуйте ещё раз позже.",
  authoringLabel: "Написать",
  createTopicHeading: "Создать новую тему",
  createTopicHelp: "Начните предметное обсуждение в этом разделе.",
  topicTitleLabel: "Название темы",
  topicTitleHelp: "Используйте ясное и конкретное название.",
  initialPostLabel: "Первое сообщение",
  createTopicSubmit: "Создать тему",
  createTopicSubmitting: "Создаём тему…",
  replyHeading: "Добавить ответ",
  replyHelp: "Добавьте полезный контекст, ответ или уточнение.",
  replyBodyLabel: "Ответ",
  replySubmit: "Опубликовать ответ",
  replySubmitting: "Публикуем ответ…",
  messageBodyHelp: "Поддерживаются Markdown и ограждённые блоки кода.",
  authoringRequiredHint: "Все поля обязательны.",
  solved: "Решено",
  markSolved: "Отметить как решённую",
  bestAnswer: "Лучший ответ",
  selectBestAnswer: "Выбрать лучшим ответом",
  problemSolvedPrompt: "Проблема решена?",
  problemSolvedYes: "Да, отметить как решённую",
  problemSolvedNo: "Нет, оставить нерешённой",
  goToSolution: "Перейти к решению",
  topicTools: "Инструменты темы",
  pinTopic: "Закрепить тему",
  unpinTopic: "Открепить тему",
  messageTools: "Инструменты сообщения",
  automaticTranslation: "Автоматический перевод",
  manualTranslation: "Ручной перевод",
  showOriginal: "Показать оригинал",
  hideOriginal: "Скрыть оригинал",
  showTranslation: "Показать перевод",
  translationRequesting: "Запрашиваем перевод…",
  translationPending: "Перевод поставлен в очередь.",
  translationProcessing: "Перевод подготавливается.",
  translationConverging: "Перевод становится доступен.",
  translationDeferred: "Перевод временно отложен.",
  translationDeferredFor: "Перевод отложен. Повторите примерно через {{seconds}} сек.",
  translationFailed: "Не удалось выполнить перевод.",
  translationUnavailable: "Перевод временно недоступен.",
  translationExplicitRequired: "Для этого длинного сообщения перевод нужно запросить вручную.",
  translationExplicitAction: "Перевести это сообщение",
  translationCurrent: "Перевод актуален.",
  translationRequestChanged: "Содержимое или состояние перевода изменилось. Проверьте текущую страницу.",
  translationRetryAfter: "Запросы на перевод ограничены. Повторите через {{seconds}} сек.",
  sourceLocaleCurrent: "Язык оригинала: {{locale}}",
  sourceLocaleCorrectionInput: "Исправить язык оригинала",
  sourceLocaleCorrectionSubmit: "Исправить язык",
  sourceLocaleCorrectionError_invalid: "Введите корректный язык оригинала в формате BCP-47.",
  sourceLocaleCorrectionError_unauthenticated: "Войдите, чтобы исправить язык оригинала.",
  sourceLocaleCorrectionError_origin: "Не удалось проверить запрос на исправление языка.",
  sourceLocaleCorrectionError_forbidden: "У вас нет права исправлять язык оригинала этого содержимого.",
  sourceLocaleCorrectionError_notFound: "Содержимое для исправления больше не существует.",
  sourceLocaleCorrectionError_conflict: "Содержимое изменилось до исправления языка оригинала. Перезагрузите страницу и попробуйте снова.",
  sourceLocaleCorrectionError_unavailable: "Не удалось исправить язык оригинала. Попробуйте ещё раз позже.",
  forumWriteError_invalid: "Заполните все обязательные поля.",
  forumWriteError_unauthenticated: "Войдите, чтобы продолжить.",
  forumWriteError_origin: "Не удалось проверить этот запрос.",
  forumWriteError_forbidden: "Только автор темы может изменить её решение.",
  forumWriteError_conflict: "Этот ответ нельзя выбрать как решение этой темы.",
  forumWriteError_notFound: "Нужный раздел или тема больше не существует.",
  forumWriteError_rateLimited: "Подождите несколько секунд перед следующей публикацией.",
  forumWriteError_unavailable: "Не удалось сохранить сообщение. Попробуйте ещё раз.",
  authorizationNav: "Права доступа",
  authorizationHeading: "Управление правами доступа",
  rolesHeading: "Роли",
  usersHeading: "Пользователи",
  roleSlug: "Идентификатор роли",
  displayName: "Отображаемое имя",
  createRole: "Создать пользовательскую роль",
  save: "Сохранить",
  deleteRole: "Удалить роль",
  builtInRole: "Встроенная",
  permissionsHeading: "Разрешения",
  effectivePermissions: "Действующие разрешения",
  assignedRole: "Назначенная роль",
  defaultRole: "Роль по умолчанию",
  overrideInherit: "Наследовать",
  overrideAllow: "Разрешить",
  overrideDeny: "Запретить",
  authorizationSaved: "Права доступа обновлены.",
  authorizationError_invalid: "Проверьте отправленные значения.",
  authorizationError_forbidden: "У вас нет права управлять доступом.",
  authorizationError_notFound: "Выбранная роль или пользователь больше не существует.",
  authorizationError_conflict: "Это изменение приведёт к блокировке доступа или роль уже назначена.",
  authorizationError_unavailable: "Управление правами доступа временно недоступно.",
} as const satisfies CommonTranslationValues;

export const hebrewCommonValues = {
  profileHeading: "פרופיל בפורום",
  profileEdit: "עריכת פרופיל",
  profileJoined: "תאריך הצטרפות",
  profileMessages: "הודעות",
  profileBestAnswers: "תשובות נבחרות",
  profileBio: "אודות",
  profileNoBio: "עדיין אין תיאור.",
  profileLinks: "קישורי פרופיל",
  profileWebsite: "אתר",
  profileBioHint: "עד 500 תווים. התיאור גלוי לכולם.",
  profileGithubHint: "קישור לפרופיל ציבורי ב־GitHub. לא חובה.",
  profileWebsiteHint: "קישור מלא מסוג HTTP או HTTPS. לא חובה.",
  profileSave: "שמירת פרופיל",
  profileSaving: "שומר…",
  profileCancel: "ביטול",
  profileSaved: "הפרופיל נשמר.",
  profileInvalid: "עד 500 תווים וקישורים ציבוריים תקינים. קישור GitHub חייב להוביל לפרופיל משתמש.",
  profileRoleUser: "חבר",
  profileRoleModerator: "מנחה",
  profileRoleAdmin: "מנהל",
  profileError_unauthenticated: "יש להתחבר כדי לערוך את הפרופיל.",
  profileError_origin: "לא ניתן לאמת את הבקשה.",
  profileError_forbidden: "אפשר לערוך רק את הפרופיל שלך.",
  profileError_notFound: "הפרופיל הזה כבר לא קיים.",
  profileError_unavailable: "לא ניתן לשמור את הפרופיל. נסו שוב.",

  productName: "Vico Forum",
  heading: "תשתית תרגום",
  stageSummary: "Stage 1 מגדיר ניתוב מודע ללוקאל ותרגום ממשק מסונכרן.",
  forumTagline: "שאלות, דיונים ותשובות מעשיות",
  primaryNavigation: "ניווט ראשי",
  skipToContent: "דילוג לתוכן",
  themeLabel: "ערכת נושא",
  lightTheme: "בהירה",
  darkTheme: "כהה",
  switchToLightTheme: "מעבר לערכת נושא בהירה",
  switchToDarkTheme: "מעבר לערכת נושא כהה",
  searchForum: "חיפוש בפורום",
  searchEyebrow: "גילוי",
  searchHeading: "חיפוש",
  searchIntro: "חפשו בכותרות הנושאים העדכניות, בהודעות ובתגיות טכנולוגיה.",
  searchInputLabel: "שאילתת חיפוש",
  searchInputPlaceholder: "הקלידו מילים מנושא, הודעה או תגית",
  searchSubmit: "חיפוש",
  searchPrompt: "הקלידו שאילתה כדי למצוא נושאים בפורום.",
  searchTooLong: "שאילתת חיפוש יכולה להכיל עד 200 תווים.",
  searchNoResults: "לא נמצאו נושאים עבור „{{query}}“.",
  searchResultsHeading: "תוצאות עבור „{{query}}“",
  searchResultCount: {
    one: "{{count}} תוצאה",
    two: "{{count}} תוצאות",
    other: "{{count}} תוצאות",
  },
  notifications: "התראות",
  notificationsUnreadLabel: "התראות, {{count}} לא נקראו",
  notificationIntro: "תגובות לנושאים ולהודעות שלך.",
  notificationEmpty: "אין לך התראות.",
  notificationReplyBy: "תגובה מאת {{actor}}",
  notificationUnread: "לא נקרא",
  notificationRead: "נקרא",
  notificationOpen: "פתיחת התגובה",
  forumHomeNav: "ראשי",
  helpSolutionsHeading: "עזרה ופתרונות",
  helpSolutionsIntro: "שאלות טכניות, פתרון תקלות ופתרונות מעשיים מהקהילה.",
  helpSolutionsAllMode: "הכול",
  helpSolutionsAllHeading: "כל השאלות",
  helpSolutionsNeedsHelpMode: "דרושה עזרה",
  helpSolutionsNeedsHelpHeading: "שאלות שזקוקות לעזרה",
  helpSolutionsNeedsHelpEmpty: "אין כרגע שאלות שזקוקות לעזרה.",
  helpSolutionsWantToHelpMode: "רוצה לעזור",
  helpSolutionsWantToHelpHeading: "שאלות שאפשר לעזור בהן",
  helpSolutionsWantToHelpEmpty: "אין כרגע שאלות פתוחות של משתמשים אחרים.",
  helpSolutionsForMeMode: "בשבילי",
  helpSolutionsForMeHeading: "שאלות בשבילי",
  helpSolutionsForMeEmpty: "אין כרגע שאלות פתוחות מתאימות בשבילך.",
  helpSolutionsActiveMode: "פעילות",
  helpSolutionsActiveHeading: "שאלות פעילות",
  helpSolutionsActiveEmpty: "אין כרגע שאלות פעילות.",
  helpSolutionsNeedsAttentionMode: "דורשות תשומת לב",
  helpSolutionsNeedsAttentionHeading: "שאלות שדורשות תשומת לב",
  helpSolutionsNeedsAttentionEmpty: "אין כרגע שאלות שדורשות תשומת לב.",
  helpSolutionsMineMode: "השאלות שלי",
  helpSolutionsMineHeading: "השאלות שלי",
  helpSolutionsMineEmpty: "עדיין לא שאלת שאלות.",
  helpSolutionsSimilarCheck: "בדיקת שאלות דומות",
  helpSolutionsSimilarChecking: "בודקים…",
  helpSolutionsSimilarHeading: "שאלות דומות",
  helpSolutionsSimilarIntro: "בדקו את השאלות הקיימות האלה לפני הפרסום. עדיין אפשר לפרסם שאלה חדשה.",
  helpSolutionsSimilarEmpty: "לא נמצאו שאלות דומות.",
  helpSolutionsSimilarInvalid: "הזינו כותרת שאלה באורך של עד 200 תווים כדי לבדוק שאלות דומות.",
  helpSolutionsSimilarUnavailable: "בדיקת שאלות דומות אינה זמינה כרגע. עדיין אפשר לפרסם את השאלה.",
  helpSolutionsSimilarMatchTitle: "נמצא בכותרת",
  helpSolutionsSimilarMatchTags: "נמצא בתגיות",
  helpSolutionsSimilarMatchBody: "נמצא בדיון",
  helpSolutionsAskHeading: "שאלו שאלה",
  helpSolutionsAskHelp: "תארו את הבעיה בצורה ברורה כדי שאחרים יוכלו לשחזר ולפתור אותה.",
  helpSolutionsQuestionTitleLabel: "כותרת השאלה",
  helpSolutionsQuestionBodyLabel: "פרטי השאלה",
  helpSolutionsAskSubmit: "שאלו שאלה",
  helpSolutionsAskSubmitting: "מפרסמים את השאלה…",
  helpSolutionsSolutionsMode: "פתרונות",
  helpSolutionsSolutionsHeading: "שאלות פתורות",
  helpSolutionsSolutionsEmpty: "עדיין אין שאלות פתורות.",
  helpSolutionNeedsReview: "דורש בדיקה",
  helpDuplicateBadge: "כפילות",
  helpDuplicateDisputed: "במחלוקת",
  helpDuplicateOf: "כפילות של",
  helpDuplicateOriginalIdLabel: "מזהה השאלה המקורית",
  helpDuplicateConfirm: "אישור כפילות",
  helpDuplicateRemove: "הסרת סימון כפילות",
  helpDuplicateAppealHeading: "ערעור על כפילות",
  helpDuplicateAppealExplanationLabel: "מדוע השאלה הזו אינה כפילות?",
  helpDuplicateAppealSubmit: "שליחת ערעור",
  helpDuplicateAppealPending: "סימון הכפילות נמצא במחלוקת.",
  helpDuplicateAppealReviewHeading: "ערעור על כפילות",
  helpDuplicateAppealAccept: "קבלת הערעור והסרת הכפילות",
  helpDuplicateAppealReject: "דחיית הערעור",
  topicAdminPanel: "לוח ניהול",
  helpSolutionOutdated: "הפתרון מיושן",
  helpSolutionOutdatedReasonLabel: "למה הפתרון מיושן",
  helpSolutionOutdatedReasonBestAnswerReplaced: "נבחרה תשובה מיטבית חדשה.",
  helpSolutionMarkNeedsReview: "סימון כדורש בדיקה",
  helpSolutionOutdatedReasonInput: "הסיבה שהפתרון מיושן",
  helpSolutionMarkOutdated: "סימון הפתרון כמיושן",
  helpSolutionClearModeration: "ניקוי סטטוס הפתרון",
  helpSolutionsEmpty: "עדיין אין שאלות.",
  helpSolutionsOpen: "פתוח",
  helpSolutionsReplyCount: {
    one: "{{count}} תגובה",
    two: "{{count}} תגובות",
    other: "{{count}} תגובות",
  },
  helpSolutionsUpdated: "עודכן {{time}}",
  helpSolutionsFiltersHeading: "מסננים",
  helpSolutionsFilterSolution: "פתרון",
  helpSolutionsFilterAnswers: "תשובות",
  helpSolutionsFilterQuality: "איכות",
  helpSolutionsFilterRelation: "קשר",
  helpSolutionsFilterAny: "הכול",
  helpSolutionsFilterUnresolved: "לא פתור",
  helpSolutionsFilterSolved: "פתור",
  helpSolutionsFilterNeedsReview: "דורש בדיקה",
  helpSolutionsFilterOutdated: "מיושן",
  helpSolutionsFilterNoAnswers: "ללא תשובות",
  helpSolutionsFilterHasAnswers: "יש תשובות",
  helpSolutionsFilterNormal: "רגיל",
  helpSolutionsFilterNeedsDetails: "נדרשים פרטים",
  helpSolutionsFilterStandalone: "עצמאי",
  helpSolutionsFilterApply: "החל",
  helpSolutionsFilterReset: "איפוס",
  unansweredNav: "ללא תשובה",
  unansweredEyebrow: "גילוי",
  unansweredHeading: "נושאים ללא מענה",
  unansweredIntro: "נושאים שעדיין לא נפתרו ולא קיבלו תשובה.",
  unansweredEmpty: "אין כרגע נושאים ללא מענה.",
  unansweredNoReplies: "עדיין אין תשובות",
  tagsNav: "תגיות",
  tagsEyebrow: "גילוי",
  tagsHeading: "תגיות טכנולוגיה",
  tagsIntro: "עיינו בנושאי הפורום לפי תגית טכנולוגיה.",
  tagsEmpty: "אין עדיין תגיות.",
  tagTopicsHeading: "נושאים עם התגית {{tag}}",
  tagTopicsIntro: "נושאי פורום שמשתמשים בתגית הזו.",
  tagTopicsEmpty: "אין נושאים עם התגית הזו.",
  tagTopicCount: {
    one: "{{count}} נושא",
    two: "{{count}} נושאים",
    other: "{{count}} נושאים",
  },
  topicTagsLabel: "תגיות",
  topicTagsInputLabel: "תגיות",
  topicTagsInputHelp: "הפרידו תגיות בפסיקים, למשל: TypeScript, Cloudflare, PostgreSQL.",
  popularNav: "פופולרי",
  popularEyebrow: "גילוי",
  popularHeading: "נושאים פופולריים",
  popularIntro: "הנושאים עם פעילות ההודעות הגבוהה ביותר בכל תקופה אחרונה.",
  popularPeriod24h: "24 שעות",
  popularPeriod7d: "7 ימים",
  popularPeriod30d: "30 ימים",
  popularEmpty: "אין פעילות בנושאים בתקופה הזו.",
  unreadNav: "לא נקראו",
  unreadEyebrow: "גילוי",
  unreadHeading: "נושאים שלא נקראו",
  unreadExistingHeading: "לא נקראו",
  unreadNewHeading: "חדשים",
  unreadIntro: "נושאים חדשים ונושאים עם הודעות שעדיין לא קראת.",
  unreadEmpty: "אין לך נושאים שלא נקראו.",
  unreadNew: "חדש",
  readStateRead: "נקרא",
  unreadCount: {
    one: "{{count}} הודעה שלא נקראה",
    two: "{{count}} הודעות שלא נקראו",
    other: "{{count}} הודעות שלא נקראו",
  },
  enterForumSection: "פתיחת {{section}}",
  forumDiscoveryDevelopmentStatus: "{{section}}: מצב פיתוח",
  footerNavigation: "ניווט בתחתית",
  rulesNav: "כללים",
  helpNav: "עזרה",
  aboutVicoNav: "על Vico",
  feedbackNav: "משוב",
  privacyNav: "פרטיות",
  homeForumSectionsHeading: "מדורי הפורום",
  pinnedHeading: "נעוצים",
  latestTopicsHeading: "נושאים אחרונים",
  homepageSectionFallbackDescription: "מדורים, דיונים ותשובות מעשיות בתחום הזה.",
  homepagePinnedEmpty: "אין עדיין נושאים נעוצים.",
  homepageLatestEmpty: "אין עדיין נושאים.",
  homepageExpand: "הצגת נושאים נוספים",
  homepageCollapse: "הצגת פחות נושאים",
  homepageMoreSections: {
    one: "הצגת עוד {{count}} מדור",
    two: "הצגת עוד {{count}} מדורים",
    other: "הצגת עוד {{count}} מדורים",
  },
  homepageFewerSections: "הצגת פחות מדורים",
  forumStatisticsHeading: "סטטיסטיקות הפורום",
  whosOnlineHeading: "מי מחובר",
  onlinePresencePending: "תצוגת משתמשים מחוברים עדיין בפיתוח.",
  onlineActiveCount: "חברים מחוברים שהיו פעילים בחמש הדקות האחרונות: {{count}}",
  onlineNoMembers: "אין כרגע חברים מחוברים פעילים.",
  onlinePresenceUnavailable: "המידע על חברים מחוברים אינו זמין כעת.",
  onlineMembersOnly: "נספרים רק חברים מחוברים; אורחים אינם במעקב.",
  viewDevelopmentStatus: "הצגת מצב הפיתוח",
  underDevelopmentEyebrow: "טרום השקה",
  underDevelopmentHeading: "בפיתוח",
  underDevelopmentIntro: "העמוד מרכז פונקציות מאושרות של Vico Forum שעדיין לא הושלמו. בתקופת טרום ההשקה נקודות הכניסה נשארות גלויות במקום לדמות פעולה שאינה קיימת.",
  underDevelopmentRequested: "{{feature}} עדיין לא הושלם.",
  underDevelopmentRemainingHeading: "עדיין בפיתוח",
  underDevelopmentBackToForum: "חזרה לפורום",
  underDevelopmentFeatureSearch: "חיפוש גלובלי בפורום",
  underDevelopmentFeatureNotifications: "התראות",
  underDevelopmentFeatureRegistration: "רישום חשבון",
  underDevelopmentFeaturePinnedTopics: "ניהול נושאים נעוצים",
  underDevelopmentFeatureUnread: "מצב חדש/לא נקרא ומעבר לראשון שלא נקרא",
  underDevelopmentFeatureDrafts: "טיוטות ושמירה אוטומטית",
  underDevelopmentFeatureProfiles: "פרופילי משתמשי הפורום",
  underDevelopmentFeatureTechnologyTags: "תגיות טכנולוגיה",
  underDevelopmentFeatureUnansweredFilter: "סינון ללא תשובה",
  underDevelopmentFeaturePopular: "נושאים פופולריים לפי תקופת פעילות",
  underDevelopmentFeatureForumDiscovery: "תצוגת קטגוריות ומדורי הפורום",
  underDevelopmentFeatureMessageLinks: "קישורים קבועים להודעות והעתקת קישור",
  underDevelopmentFeatureReplyQuote: "קשרים של תגובה וציטוט",
  underDevelopmentFeatureEditor: "עורך מלא וכלי קוד",
  underDevelopmentFeatureOnlinePresence: "מי מחובר",
  underDevelopmentFeatureRules: "עמוד כללי הפורום",
  underDevelopmentFeatureHelp: "עמוד עזרה",
  underDevelopmentFeatureAbout: "על Vico",
  underDevelopmentFeatureFeedback: "משוב",
  underDevelopmentFeaturePrivacy: "עמוד פרטיות",
  authEmailHeading: "כניסה ל־Vico Forum",
  authRegisterHeading: "יצירת חשבון",
  authEmailName: "שם תצוגה",
  authEmailAddress: "דוא״ל",
  authEmailPassword: "סיסמה",
  authEmailPasswordHint: "8–128 תווים.",
  authEmailSubmit: "כניסה באמצעות דוא״ל",
  authRegisterSubmit: "יצירת חשבון",
  authGoogleOption: "המשך עם Google",
  authSwitchToRegister: "אין לך חשבון? הרשמה",
  authSwitchToSignIn: "כבר יש לך חשבון? כניסה",
  authEmailFailure: "הכניסה נכשלה. יש לבדוק את הדוא״ל והסיסמה.",
  authRegisterFailure: "יצירת החשבון נכשלה. יש לבדוק את הפרטים או להשתמש בדוא״ל אחר.",
  authEmailNoVerification: "אימות דוא״ל ושחזור סיסמה עדיין אינם זמינים.",
  signInGoogle: "כניסה",
  signUp: "הרשמה",
  signOut: "יציאה",
  authPending: "נא להמתין…",
  authError: "ההתחברות נכשלה. נסו שוב.",
  forumIndex: "ראשי",
  categoriesHeading: "קטגוריות",
  categoriesIntro: "עיון בפורום לפי קטגוריה ומדור.",
  categoriesEmpty: "אין עדיין קטגוריות.",
  sectionsEmpty: "אין עדיין מדורים בקטגוריה הזו.",
  topicsEmpty: "אין עדיין נושאים במדור הזה.",
  postsEmpty: "אין עדיין הודעות בנושא הזה.",
  breadcrumbsLabel: "פירורי לחם",
  categoryLabel: "קטגוריה",
  sectionLabel: "מדור",
  topicLabel: "נושא",
  topicsHeading: "נושאים",
  topicColumn: "נושא",
  postsColumn: "הודעות",
  sectionCount: {
    one: "{{count}} מדור",
    two: "{{count}} מדורים",
    other: "{{count}} מדורים",
  },
  topicCount: {
    one: "{{count}} נושא",
    two: "{{count}} נושאים",
    other: "{{count}} נושאים",
  },
  messageCount: {
    one: "{{count}} הודעה",
    two: "{{count}} הודעות",
    other: "{{count}} הודעות",
  },
  startedBy: "נפתח על ידי {{author}}",
  postNumber: "הודעה #{{number}}",
  copyMessageLink: "העתקת קישור",
  copyMessageLinkFor: "העתקת קישור אל {{message}}",
  messageLinkCopied: "הועתק",
  messageLinkCopyFailed: "לא ניתן להעתיק את הקישור.",
  messageActions: "פעולות",
  replyToMessage: "תגובה",
  quoteSelectedText: "ציטוט",
  replyToMessageNumber: "תגובה להודעה #{{number}}",
  replyToMessageNumberCompact: "תגובה ל־#{{number}}",
  directReplies: "תגובות ישירות",
  directRepliesCompact: "תגובות",
  replyingToMessage: "תגובה להודעה #{{number}}",
  clearReplyTarget: "תגובה לנושא במקום זאת",
  quoteSelectionRequired: "בחרו טקסט בהודעה הזו כדי לצטט אותו.",
  originalQuestion: "השאלה המקורית",
  systemStateEyebrow: "מצב מערכת",
  routeBackToForum: "חזרה לפורום",
  routeUnauthenticatedHeading: "נדרשת התחברות",
  routeUnauthenticatedBody: "התחברו לחשבון כדי לפתוח את העמוד הזה.",
  routeForbiddenHeading: "הגישה נדחתה",
  routeForbiddenBody: "אין לכם הרשאה לצפות בעמוד הזה.",
  routeUnavailableHeading: "לא זמין זמנית",
  routeUnavailableBody: "חלק זה של Vico Forum אינו זמין זמנית. נסו שוב מאוחר יותר.",
  forumNotFoundHeading: "עמוד הפורום לא נמצא",
  forumNotFoundBody: "הקטגוריה, המדור או הנושא אינם קיימים.",
  forumErrorHeading: "לא ניתן לטעון את הפורום",
  forumErrorBody: "נסו שוב מאוחר יותר.",
  authoringLabel: "כתיבה",
  createTopicHeading: "יצירת נושא חדש",
  createTopicHelp: "פתחו דיון ממוקד במדור הזה.",
  topicTitleLabel: "כותרת הנושא",
  topicTitleHelp: "השתמשו בכותרת ברורה ומדויקת.",
  initialPostLabel: "הודעה ראשונה",
  createTopicSubmit: "יצירת נושא",
  createTopicSubmitting: "יוצר נושא…",
  replyHeading: "הוספת תגובה",
  replyHelp: "הוסיפו הקשר מועיל, תשובה או המשך.",
  replyBodyLabel: "תגובה",
  replySubmit: "פרסום תגובה",
  replySubmitting: "מפרסם תגובה…",
  messageBodyHelp: "Markdown ובלוקי קוד מגודרים נתמכים.",
  authoringRequiredHint: "כל השדות נדרשים.",
  solved: "נפתר",
  markSolved: "סימון כנפתר",
  bestAnswer: "התשובה הטובה ביותר",
  selectBestAnswer: "בחירה כתשובה הטובה ביותר",
  problemSolvedPrompt: "הבעיה נפתרה?",
  problemSolvedYes: "כן, לסמן כנפתרה",
  problemSolvedNo: "לא, להשאיר לא פתורה",
  goToSolution: "מעבר לפתרון",
  topicTools: "כלי נושא",
  pinTopic: "נעיצת נושא",
  unpinTopic: "ביטול נעיצת נושא",
  messageTools: "כלי הודעה",
  automaticTranslation: "תרגום אוטומטי",
  manualTranslation: "תרגום ידני",
  showOriginal: "הצגת המקור",
  hideOriginal: "הסתר את המקור",
  showTranslation: "הצגת התרגום",
  translationRequesting: "מבקש תרגום…",
  translationPending: "התרגום נוסף לתור.",
  translationProcessing: "התרגום בהכנה.",
  translationConverging: "התרגום הופך לזמין.",
  translationDeferred: "התרגום נדחה זמנית.",
  translationDeferredFor: "התרגום נדחה. נסו שוב בעוד כ-{{seconds}} שניות.",
  translationFailed: "לא ניתן היה להשלים את התרגום.",
  translationUnavailable: "התרגום אינו זמין זמנית.",
  translationExplicitRequired: "הודעה ארוכה זו דורשת בקשת תרגום מפורשת.",
  translationExplicitAction: "תרגום ההודעה הזו",
  translationCurrent: "התרגום עדכני.",
  translationRequestChanged: "התוכן או מצב התרגום השתנו. בדקו את העמוד הנוכחי.",
  translationRetryAfter: "בקשות התרגום מוגבלות. נסו שוב בעוד {{seconds}} שניות.",
  sourceLocaleCurrent: "שפת המקור: {{locale}}",
  sourceLocaleCorrectionInput: "תיקון שפת המקור",
  sourceLocaleCorrectionSubmit: "תיקון השפה",
  sourceLocaleCorrectionError_invalid: "הזינו שפת מקור תקינה בפורמט BCP-47.",
  sourceLocaleCorrectionError_unauthenticated: "התחברו כדי לתקן את שפת המקור.",
  sourceLocaleCorrectionError_origin: "לא ניתן היה לאמת את בקשת תיקון השפה.",
  sourceLocaleCorrectionError_forbidden: "אין לכם הרשאה לתקן את שפת המקור של התוכן הזה.",
  sourceLocaleCorrectionError_notFound: "התוכן לתיקון כבר אינו קיים.",
  sourceLocaleCorrectionError_conflict: "התוכן השתנה לפני שניתן היה לתקן את שפת המקור. טענו מחדש ונסו שוב.",
  sourceLocaleCorrectionError_unavailable: "לא ניתן היה לתקן את שפת המקור. נסו שוב מאוחר יותר.",
  forumWriteError_invalid: "מלאו את כל שדות החובה.",
  forumWriteError_unauthenticated: "התחברו כדי להמשיך.",
  forumWriteError_origin: "לא ניתן היה לאמת את הבקשה.",
  forumWriteError_forbidden: "רק מחבר הנושא יכול לשנות את הפתרון שלו.",
  forumWriteError_conflict: "לא ניתן לבחור את התשובה הזו כפתרון לנושא הזה.",
  forumWriteError_notFound: "המדור או הנושא המבוקש כבר אינם קיימים.",
  forumWriteError_rateLimited: "המתינו כמה שניות לפני פרסום נוסף.",
  forumWriteError_unavailable: "לא ניתן היה לשמור את ההודעה. נסו שוב.",
  authorizationNav: "הרשאות",
  authorizationHeading: "ניהול הרשאות",
  rolesHeading: "תפקידים",
  usersHeading: "משתמשים",
  roleSlug: "מזהה תפקיד",
  displayName: "שם תצוגה",
  createRole: "יצירת תפקיד מותאם",
  save: "שמירה",
  deleteRole: "מחיקת תפקיד",
  builtInRole: "מובנה",
  permissionsHeading: "הרשאות",
  effectivePermissions: "הרשאות בפועל",
  assignedRole: "תפקיד משויך",
  defaultRole: "תפקיד ברירת מחדל",
  overrideInherit: "ירושה",
  overrideAllow: "אפשר",
  overrideDeny: "חסום",
  authorizationSaved: "ההרשאות עודכנו.",
  authorizationError_invalid: "בדקו את הערכים שנשלחו.",
  authorizationError_forbidden: "אין לכם הרשאה לנהל הרשאות.",
  authorizationError_notFound: "התפקיד או המשתמש שנבחרו כבר אינם קיימים.",
  authorizationError_conflict: "השינוי יגרום לחסימת גישה או שהתפקיד כבר משויך.",
  authorizationError_unavailable: "ניהול ההרשאות אינו זמין זמנית.",
} as const satisfies CommonTranslationValues;
